// ============================================================
// DATA.JS â€” Ãlbum Panini Mundial 2026
// NOTA: Grupos basados en el sorteo oficial FIFA (5 dic 2024).
// Jugadores segÃºn convocatorias mÃ¡s recientes. Marcar // verificar
// donde hay incertidumbre. Actualiza este archivo si hay cambios.
// ============================================================

const POSITIONS = { POR: 'Portero', DEF: 'Defensa', MED: 'Mediocampista', DEL: 'Delantero' };

const SPECIAL_STICKERS = [
  { code: 'SEC-01', name: 'PresentaciÃ³n del torneo' },
  { code: 'SEC-02', name: 'Historia del Mundial' },
  { code: 'SEC-03', name: 'Mascota oficial' },
  { code: 'SEC-04', name: 'BalÃ³n oficial' },
  { code: 'SEC-05', name: 'Trofeo FIFA' },
  { code: 'SEC-06', name: 'Estadio AT&T (Arlington)' },
  { code: 'SEC-07', name: 'Estadio Rose Bowl (LA)' },
  { code: 'SEC-08', name: 'Estadio MetLife (NJ)' },
  { code: 'SEC-09', name: 'Estadio Levi\'s (SF)' },
  { code: 'SEC-10', name: 'Estadio Arrowhead (KC)' },
  { code: 'SEC-11', name: 'Estadio Lincoln Financial (Phil)' },
  { code: 'SEC-12', name: 'Estadio Gillette (Boston)' },
  { code: 'SEC-13', name: 'Estadio NRG (Houston)' },
  { code: 'SEC-14', name: 'Estadio Allegiant (LV)' },
  { code: 'SEC-15', name: 'Estadio Seattle' },
  { code: 'SEC-16', name: 'Estadio BC Place (Vancouver)' },
  { code: 'SEC-17', name: 'Estadio Azteca (Ciudad de MÃ©xico)' },
  { code: 'SEC-18', name: 'Estadio Estadio BBVA (Monterrey)' },
  { code: 'SEC-19', name: 'Calendario de partidos' },
  { code: 'SEC-20', name: 'Sede y organizadores' },
];

const EXTRA_STICKERS = [
  // Dorados (7)
  { code: 'EXT-G01', name: 'Lionel Messi', team: 'ARG', variant: 'gold' },
  { code: 'EXT-G02', name: 'Kylian MbappÃ©', team: 'FRA', variant: 'gold' },
  { code: 'EXT-G03', name: 'Erling Haaland', team: 'NOR', variant: 'gold' }, // verificar
  { code: 'EXT-G04', name: 'VinÃ­cius Jr.', team: 'BRA', variant: 'gold' },
  { code: 'EXT-G05', name: 'Jude Bellingham', team: 'ENG', variant: 'gold' },
  { code: 'EXT-G06', name: 'Cristiano Ronaldo', team: 'POR', variant: 'gold' },
  { code: 'EXT-G07', name: 'Lautaro MartÃ­nez', team: 'ARG', variant: 'gold' },
  // Plateados (8)
  { code: 'EXT-S01', name: 'Son Heung-min', team: 'KOR', variant: 'silver' },
  { code: 'EXT-S02', name: 'Mohamed Salah', team: 'EGY', variant: 'silver' },
  { code: 'EXT-S03', name: 'Kevin De Bruyne', team: 'BEL', variant: 'silver' },
  { code: 'EXT-S04', name: 'Harry Kane', team: 'ENG', variant: 'silver' },
  { code: 'EXT-S05', name: 'Rodri', team: 'ESP', variant: 'silver' },
  { code: 'EXT-S06', name: 'Pedri', team: 'ESP', variant: 'silver' },
  { code: 'EXT-S07', name: 'Florian Wirtz', team: 'GER', variant: 'silver' },
  { code: 'EXT-S08', name: 'Bukayo Saka', team: 'ENG', variant: 'silver' },
  // Bronce (7)
  { code: 'EXT-B01', name: 'Luis DÃ­az', team: 'COL', variant: 'bronze' },
  { code: 'EXT-B02', name: 'Darwin NÃºÃ±ez', team: 'URU', variant: 'bronze' },
  { code: 'EXT-B03', name: 'Victor Osimhen', team: 'NGA', variant: 'bronze' },
  { code: 'EXT-B04', name: 'Takefusa Kubo', team: 'JPN', variant: 'bronze' },
  { code: 'EXT-B05', name: 'Frenkie de Jong', team: 'NED', variant: 'bronze' },
  { code: 'EXT-B06', name: 'Gavi', team: 'ESP', variant: 'bronze' },
  { code: 'EXT-B07', name: 'Federico Valverde', team: 'URU', variant: 'bronze' },
];

const ADDITIONAL_SECTIONS = [
  {
    code: 'FWC',
    name: 'FIFA World Cup',
    icon: 'FWC',
    group: 'Especiales',
    stickers: [
      { code: '00', name: 'Lamina 00', type: 'album-special' },
      ...[
        'FWC1', 'FWC2', 'FWC3', 'FWC4', 'FWC5', 'FWC6', 'FWC7', 'FWC8', 'FWC9',
        'FWC10', 'FWC11', 'FWC12', 'FWC13', 'FWC14', 'FWC15', 'FWC16', 'FWC17', 'FWC18', 'FWC19'
      ].map(code => ({ code, name: code, type: 'album-special' }))
    ]
  },
  {
    code: 'CC',
    name: 'Coca-Cola',
    icon: 'CC',
    group: 'Coca-Cola',
    stickers: [
      'CC1', 'CC2', 'CC3', 'CC4', 'CC5', 'CC6', 'CC7',
      'CC8', 'CC9', 'CC10', 'CC11', 'CC12', 'CC13', 'CC14'
    ].map(code => ({ code, name: code, type: 'sponsor' }))
  }
];

// Helper para generar stickers de un equipo
function makeTeam(code, name, flag, group, debutant, players) {
  return {
    code, name, flag, group, debutant,
    stickers: Array.from({ length: 20 }, (_, i) => {
      const number = i + 1;
      const stickerCode = `${code}${number}`;
      if (number === 1) return { code: stickerCode, name: stickerCode, type: 'shield' };
      if (number === 13) return { code: stickerCode, name: stickerCode, type: 'group' };
      return { code: stickerCode, name: stickerCode, type: 'sticker' };
    })
  };
}

const TEAMS_DATA = [
  // â”€â”€ GRUPO A â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  makeTeam('MEX', 'México', 'MEX', 'A', false, [
    ['Guillermo Ochoa', 'Portero'],
    ['Luis MalagÃ³n', 'Portero'],
    ['Rodolfo Cota', 'Portero'],
    ['Jorge SÃ¡nchez', 'Defensa'],
    ['CÃ©sar Montes', 'Defensa'],
    ['Johan VÃ¡squez', 'Defensa'],
    ['Gerardo Arteaga', 'Defensa'],
    ['JuliÃ¡n AraÃºjo', 'Defensa'],
    ['Jorge Moreno', 'Defensa'], // verificar
    ['Edson Ãlvarez', 'Mediocampista'],
    ['Carlos RodrÃ­guez', 'Mediocampista'],
    ['OrbelÃ­n Pineda', 'Mediocampista'],
    ['Roberto Alvarado', 'Mediocampista'],
    ['Luis Romo', 'Mediocampista'], // verificar
    ['Ã‰rick GutiÃ©rrez', 'Mediocampista'], // verificar
    ['Hirving Lozano', 'Delantero'],
    ['Henry MartÃ­n', 'Delantero'],
    ['Santiago GimÃ©nez', 'Delantero'],
  ]),
  makeTeam('RSA', 'Sudáfrica', 'RSA', 'A', false, [
    ['HernÃ¡n GalÃ­ndez', 'Portero'],
    ['Alexander DomÃ­nguez', 'Portero'],
    ['Wellington RamÃ­rez', 'Portero'], // verificar
    ['Piero HincapiÃ©', 'Defensa'],
    ['Byron Castillo', 'Defensa'],
    ['Pervis EstupiÃ±Ã¡n', 'Defensa'],
    ['Jackson Porozo', 'Defensa'],
    ['Diego Palacios', 'Defensa'],
    ['FÃ©lix Torres', 'Defensa'],
    ['Carlos Gruezo', 'Mediocampista'],
    ['MoisÃ©s Caicedo', 'Mediocampista'],
    ['Jhegson MÃ©ndez', 'Mediocampista'],
    ['Ãngel Mena', 'Mediocampista'],
    ['Jeremy Sarmiento', 'Mediocampista'],
    ['Gonzalo Plata', 'Mediocampista'],
    ['Enner Valencia', 'Delantero'],
    ['Michael Estrada', 'Delantero'],
    ['Jordy Caicedo', 'Delantero'], // verificar
  ]),
  makeTeam('KOR', 'Korea Republic', 'KOR', 'A', false, [
    ['Ã‰douard Mendy', 'Portero'],
    ['SÃ©ny Dieng', 'Portero'],
    ['Alfred Gomis', 'Portero'],
    ['Kalidou Koulibaly', 'Defensa'],
    ['Abdou Diallo', 'Defensa'],
    ['FodÃ© Ballo-TourÃ©', 'Defensa'],
    ['Youssouf Sabaly', 'Defensa'],
    ['Moussa NiakhatÃ©', 'Defensa'],
    ['Formose Mendy', 'Defensa'], // verificar
    ['Cheikhou KouyatÃ©', 'Mediocampista'],
    ['Nampalys Mendy', 'Mediocampista'],
    ['Pape Gueye', 'Mediocampista'],
    ['Krepin Diatta', 'Mediocampista'],
    ['PathÃ© Ciss', 'Mediocampista'],
    ['Lamine Camara', 'Mediocampista'], // verificar
    ['Sadio ManÃ©', 'Delantero'],
    ['IsmaÃ¯la Sarr', 'Delantero'],
    ['Habib Diallo', 'Delantero'],
  ]),
  makeTeam('CZE', 'Czechia', 'CZE', 'A', false, [ // verificar grupo
    ['Florin NiÈ›Äƒ', 'Portero'],
    ['HoraÈ›iu Moldovan', 'Portero'],
    ['È˜tefan TÃ¢rnovanu', 'Portero'],
    ['Andrei RaÈ›iu', 'Defensa'],
    ['Radu DrÄƒguÈ™in', 'Defensa'],
    ['Cristian Manea', 'Defensa'],
    ['Adrian Rus', 'Defensa'],
    ['IonuÈ› Nedelcearu', 'Defensa'],
    ['Bogdan RacoviÈ›an', 'Defensa'],
    ['Razvan Marin', 'Mediocampista'],
    ['Deian Sorescu', 'Mediocampista'],
    ['NicuÈ™or Bancu', 'Mediocampista'],
    ['Octavian Popescu', 'Mediocampista'],
    ['Dennis Man', 'Mediocampista'],
    ['Alexandru IoniÈ›Äƒ', 'Mediocampista'], // verificar
    ['Denis Alibec', 'Delantero'],
    ['Florinel Coman', 'Delantero'],
    ['George PuÈ™caÈ™', 'Delantero'],
  ]),

  // â”€â”€ GRUPO B â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  makeTeam('CAN', 'Canadá', 'CAN', 'B', false, [
    ['Maxime CrÃ©peau', 'Portero'],
    ['Milan Borjan', 'Portero'],
    ['James Pantemis', 'Portero'],
    ['Alistair Johnston', 'Defensa'],
    ['Kamal Miller', 'Defensa'],
    ['Doneil Henry', 'Defensa'],
    ['Derek Cornelius', 'Defensa'],
    ['Scott Kennedy', 'Defensa'],
    ['Richie Laryea', 'Defensa'],
    ['Atiba Hutchinson', 'Mediocampista'],
    ['Stephen EustÃ¡quio', 'Mediocampista'],
    ['Jonathan Osorio', 'Mediocampista'],
    ['Samuel Piette', 'Mediocampista'],
    ['Mark-Anthony Kaye', 'Mediocampista'],
    ['Liam Millar', 'Mediocampista'], // verificar
    ['Alphonso Davies', 'Delantero'],
    ['Jonathan David', 'Delantero'],
    ['Cyle Larin', 'Delantero'],
  ]),
  makeTeam('BIH', 'Bosnia y Herzegovina', 'BIH', 'B', false, [
    ['Yassine Bounou', 'Portero'],
    ['Munir Mohamedi', 'Portero'],
    ['Ahmed Tagnaouti', 'Portero'],
    ['Noussair Mazraoui', 'Defensa'],
    ['Achraf Hakimi', 'Defensa'],
    ['Romain SaÃ¯ss', 'Defensa'],
    ['Nayef Aguerd', 'Defensa'],
    ['Jawad El-Yamiq', 'Defensa'],
    ['Adam Masina', 'Defensa'],
    ['Azzedine Ounahi', 'Mediocampista'],
    ['Sofyan Amrabat', 'Mediocampista'],
    ['Selim Amallah', 'Mediocampista'],
    ['Ilias Chair', 'Mediocampista'],
    ['Bilal El Khannouss', 'Mediocampista'],
    ['Abde Ezzalzouli', 'Mediocampista'],
    ['Hakim Ziyech', 'Delantero'],
    ['Youssef En-Nesyri', 'Delantero'],
    ['Soufiane Boufal', 'Delantero'],
  ]),
  makeTeam('QAT', 'Qatar', 'QAT', 'B', false, [
    ['Dominik LivakoviÄ‡', 'Portero'],
    ['Ivo GrbiÄ‡', 'Portero'],
    ['Nedeljko LabroviÄ‡', 'Portero'],
    ['Josip Å utalo', 'Defensa'],
    ['Duje Ä†aleta-Car', 'Defensa'],
    ['JoÅ¡ko Gvardiol', 'Defensa'],
    ['Borna Sosa', 'Defensa'],
    ['Josip JuranoviÄ‡', 'Defensa'],
    ['Domagoj Vida', 'Defensa'], // verificar
    ['Luka ModriÄ‡', 'Mediocampista'],
    ['Marcelo BrozoviÄ‡', 'Mediocampista'],
    ['Mateo KovaÄiÄ‡', 'Mediocampista'],
    ['Mario PaÅ¡aliÄ‡', 'Mediocampista'],
    ['Lovro Majer', 'Mediocampista'],
    ['Luka SuÄiÄ‡', 'Mediocampista'],
    ['Ante Budimir', 'Delantero'],
    ['Ivan PeriÅ¡iÄ‡', 'Delantero'],
    ['Andrej KramariÄ‡', 'Delantero'],
  ]),
  makeTeam('SUI', 'Suiza', 'SUI', 'B', false, [
    ['Luis MejÃ­a', 'Portero'],
    ['Orlando Mosquera', 'Portero'],
    ['Gianluca Cariolato', 'Portero'],
    ['Michael Murillo', 'Defensa'],
    ['Harold Cummings', 'Defensa'],
    ['Fidel Escobar', 'Defensa'],
    ['Eric Davis', 'Defensa'],
    ['Roderick Miller', 'Defensa'],
    ['AndrÃ©s Andrade', 'Defensa'],
    ['Adalberto Carrasquilla', 'Mediocampista'],
    ['Alberto Quintero', 'Mediocampista'],
    ['AnÃ­bal Godoy', 'Mediocampista'],
    ['Edgar BÃ¡rcenas', 'Mediocampista'],
    ['Ãlex RodrÃ­guez', 'Mediocampista'], // verificar
    ['Abdiel Ayarza', 'Mediocampista'], // verificar
    ['Ismael DÃ­az', 'Delantero'],
    ['Cecilio Waterman', 'Delantero'],
    ['JosÃ© Fajardo', 'Delantero'],
  ]),

  // â”€â”€ GRUPO C â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  makeTeam('BRA', 'Brasil', 'BRA', 'C', false, [
    ['Alisson', 'Portero'],
    ['Ã‰derson', 'Portero'],
    ['Weverton', 'Portero'],
    ['Danilo', 'Defensa'],
    ['Ã‰der MilitÃ£o', 'Defensa'],
    ['Marquinhos', 'Defensa'],
    ['Gabriel MagalhÃ£es', 'Defensa'],
    ['Guilherme Arana', 'Defensa'],
    ['Alex Sandro', 'Defensa'], // verificar
    ['Casemiro', 'Mediocampista'],
    ['Bruno GuimarÃ£es', 'Mediocampista'],
    ['Lucas PaquetÃ¡', 'Mediocampista'],
    ['Raphinha', 'Mediocampista'],
    ['Rodrygo', 'Mediocampista'],
    ['Gerson', 'Mediocampista'],
    ['VinÃ­cius Jr.', 'Delantero'],
    ['Endrick', 'Delantero'],
    ['Gabriel Martinelli', 'Delantero'],
  ]),
  makeTeam('MAR', 'Marruecos', 'MAR', 'C', false, [
    ['Shuichi Gonda', 'Portero'],
    ['Daniel Schmidt', 'Portero'],
    ['Zion Suzuki', 'Portero'],
    ['Hiroki Sakai', 'Defensa'],
    ['Maya Yoshida', 'Defensa'],
    ['Ko Itakura', 'Defensa'],
    ['Shogo Taniguchi', 'Defensa'],
    ['Yuto Nagatomo', 'Defensa'],
    ['Miki Yamane', 'Defensa'],
    ['Wataru EndÅ', 'Mediocampista'],
    ['Hidemasa Morita', 'Mediocampista'],
    ['Junya Ito', 'Mediocampista'],
    ['Takefusa Kubo', 'Mediocampista'],
    ['Kaoru Mitoma', 'Mediocampista'],
    ['Daichi Kamada', 'Mediocampista'],
    ['Ritsu Doan', 'Delantero'],
    ['Ayase Ueda', 'Delantero'],
    ['Shuto Machino', 'Delantero'], // verificar
  ]),
  makeTeam('HAI', 'Haití', 'HAI', 'C', false, [
    ['AndrÃ© Onana', 'Portero'],
    ['Devis Epassy', 'Portero'],
    ['Simon Ngapandouetnbu', 'Portero'],
    ['Collins Fai', 'Defensa'],
    ['Ambroise Oyongo', 'Defensa'],
    ['Jean-Charles Castelletto', 'Defensa'],
    ['Enzo Tchato', 'Defensa'],
    ['Olivier Mbaizo', 'Defensa'],
    ['Christopher Wooh', 'Defensa'],
    ['Martin Hongla', 'Mediocampista'],
    ['AndrÃ© Zambo Anguissa', 'Mediocampista'],
    ['Samuel Gouet', 'Mediocampista'],
    ['GaÃ«l Ondoua', 'Mediocampista'], // verificar
    ['Pierre Kunde', 'Mediocampista'],
    ['Olivier Ntcham', 'Mediocampista'], // verificar
    ['Vincent Aboubakar', 'Delantero'],
    ['Karl Toko Ekambi', 'Delantero'],
    ['Bryan Mbeumo', 'Delantero'],
  ]),
  makeTeam('SCO', 'Escocia', 'SCO', 'C', false, [ // verificar grupo
    ['Stefan Marinovic', 'Portero'],
    ['Michael Woud', 'Portero'],
    ['Max Crocombe', 'Portero'],
    ['Michael Boxall', 'Defensa'],
    ['Winston Reid', 'Defensa'],
    ['Liberato Cacace', 'Defensa'],
    ['Nando de Wys', 'Defensa'],
    ['Elijah Just', 'Defensa'],
    ['Louis Fenton', 'Defensa'], // verificar
    ['Joe Bell', 'Mediocampista'],
    ['Clayton Lewis', 'Mediocampista'],
    ['Callum McCowatt', 'Mediocampista'],
    ['Garbhan Coughlan', 'Mediocampista'], // verificar
    ['Kosta Barbarouses', 'Mediocampista'],
    ['Ryan Thomas', 'Mediocampista'],
    ['Chris Wood', 'Delantero'],
    ['Matthew Garbett', 'Delantero'],
    ['Dane Ingham', 'Delantero'], // verificar
  ]),

  // â”€â”€ GRUPO D â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  makeTeam('USA', 'Estados Unidos', 'USA', 'D', false, [
    ['Matt Turner', 'Portero'],
    ['Ethan Horvath', 'Portero'],
    ['Gabriel Slonina', 'Portero'],
    ['SergiÃ±o Dest', 'Defensa'],
    ['Tim Ream', 'Defensa'],
    ['Chris Richards', 'Defensa'],
    ['Miles Robinson', 'Defensa'],
    ['Joe Scally', 'Defensa'],
    ['Antonee Robinson', 'Defensa'],
    ['Tyler Adams', 'Mediocampista'],
    ['Weston McKennie', 'Mediocampista'],
    ['Yunus Musah', 'Mediocampista'],
    ['Luca de la Torre', 'Mediocampista'],
    ['Gio Reyna', 'Mediocampista'],
    ['Brenden Aaronson', 'Mediocampista'],
    ['Christian Pulisic', 'Delantero'],
    ['Josh Sargent', 'Delantero'],
    ['Folarin Balogun', 'Delantero'],
  ]),
  makeTeam('PAR', 'Paraguay', 'PAR', 'D', false, [
    ['Mohammed Al-Owais', 'Portero'],
    ['Nawaf Al-Aqidi', 'Portero'],
    ['Yasser Al-Mosailem', 'Portero'],
    ['Saud Abdulhamid', 'Defensa'],
    ['Ali Al-Bulaihi', 'Defensa'],
    ['Hassan Tambakti', 'Defensa'],
    ['Abdulellah Al-Amri', 'Defensa'],
    ['Abdullah Madu', 'Defensa'],
    ['Sultan Al-Ghannam', 'Defensa'], // verificar
    ['Salman Al-Faraj', 'Mediocampista'],
    ['Mohammed Kanno', 'Mediocampista'],
    ['Nasser Al-Dawsari', 'Mediocampista'],
    ['Riyadh Sharahili', 'Mediocampista'],
    ['Sami Al-Najei', 'Mediocampista'], // verificar
    ['Hattan Bahbri', 'Mediocampista'], // verificar
    ['Salem Al-Dawsari', 'Delantero'],
    ['Firas Al-Buraikan', 'Delantero'],
    ['Abdullah Al-Hamdan', 'Delantero'],
  ]),
  makeTeam('AUS', 'Australia', 'AUS', 'D', false, [
    ['Yann Sommer', 'Portero'],
    ['Gregor Kobel', 'Portero'],
    ['Philipp KÃ¶hn', 'Portero'],
    ['Manuel Akanji', 'Defensa'],
    ['Nico Elvedi', 'Defensa'],
    ['Fabian SchÃ¤r', 'Defensa'],
    ['Ricardo RodrÃ­guez', 'Defensa'],
    ['Silvan Widmer', 'Defensa'],
    ['Kevin Mbabu', 'Defensa'],
    ['Granit Xhaka', 'Mediocampista'],
    ['Remo Freuler', 'Mediocampista'],
    ['Michel Aebischer', 'Mediocampista'],
    ['Xherdan Shaqiri', 'Mediocampista'],
    ['Fabian Frei', 'Mediocampista'], // verificar
    ['Dan Ndoye', 'Mediocampista'],
    ['Breel Embolo', 'Delantero'],
    ['Noah Okafor', 'Delantero'],
    ['Haris SeferoviÄ‡', 'Delantero'],
  ]),
  makeTeam('TUR', 'Turquía', 'TUR', 'D', false, [
    ['Lawrence Ati-Zigi', 'Portero'],
    ['Ibrahim Danlad', 'Portero'],
    ['Joe Wollacott', 'Portero'],
    ['Alexander Djiku', 'Defensa'],
    ['Daniel Amartey', 'Defensa'],
    ['Mohammed Salisu', 'Defensa'],
    ['Tariq Lamptey', 'Defensa'],
    ['Dennis Odoi', 'Defensa'],
    ['Baba Abdul Rahman', 'Defensa'],
    ['Thomas Partey', 'Mediocampista'],
    ['Idrissu Baba', 'Mediocampista'],
    ['AndrÃ© Ayew', 'Mediocampista'],
    ['Salis Abdul Samed', 'Mediocampista'],
    ['Osman Bukari', 'Mediocampista'],
    ['Jordan Ayew', 'Mediocampista'],
    ['Inaki Williams', 'Delantero'],
    ['Antoine Semenyo', 'Delantero'],
    ['Kamaldeen Sulemana', 'Delantero'],
  ]),

  // â”€â”€ GRUPO E â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  makeTeam('GER', 'Alemania', 'GER', 'E', false, [
    ['Manuel Neuer', 'Portero'],
    ['Marc-AndrÃ© ter Stegen', 'Portero'],
    ['Oliver Baumann', 'Portero'],
    ['Joshua Kimmich', 'Defensa'],
    ['Antonio RÃ¼diger', 'Defensa'],
    ['Jonathan Tah', 'Defensa'],
    ['David Raum', 'Defensa'],
    ['Thilo Kehrer', 'Defensa'],
    ['Benjamin Henrichs', 'Defensa'],
    ['Ilkay GÃ¼ndoÄŸan', 'Mediocampista'],
    ['Leon Goretzka', 'Mediocampista'],
    ['Florian Wirtz', 'Mediocampista'],
    ['Jamal Musiala', 'Mediocampista'],
    ['Thomas MÃ¼ller', 'Mediocampista'],
    ['Kai Havertz', 'Mediocampista'],
    ['Leroy SanÃ©', 'Delantero'],
    ['Serge Gnabry', 'Delantero'],
    ['Niclas FÃ¼llkrug', 'Delantero'],
  ]),
  makeTeam('CUW', 'Curazao', 'CUW', 'E', false, [
    ['Mathew Ryan', 'Portero'],
    ['Danny Vukovic', 'Portero'],
    ['Joe Gauci', 'Portero'],
    ['MiloÅ¡ Degenek', 'Defensa'],
    ['Harry Souttar', 'Defensa'],
    ['Aziz Behich', 'Defensa'],
    ['Jason Davidson', 'Defensa'],
    ['Nathaniel Atkinson', 'Defensa'],
    ['Fran Karacic', 'Defensa'], // verificar
    ['Aaron Mooy', 'Mediocampista'],
    ['Jackson Irvine', 'Mediocampista'],
    ['Riley McGree', 'Mediocampista'],
    ['Ajdin Hrustic', 'Mediocampista'],
    ['Cameron Devlin', 'Mediocampista'],
    ['Connor Metcalfe', 'Mediocampista'], // verificar
    ['Mathew Leckie', 'Delantero'],
    ['Mitchell Duke', 'Delantero'],
    ['Martin Boyle', 'Delantero'],
  ]),
  makeTeam('CIV', 'Costa de Marfil', 'CIV', 'E', false, [
    ['Predrag RajkoviÄ‡', 'Portero'],
    ['Vanja MilinkoviÄ‡-SaviÄ‡', 'Portero'],
    ['Marko DmitroviÄ‡', 'Portero'],
    ['Strahinja PavloviÄ‡', 'Defensa'],
    ['MiloÅ¡ VeljkoviÄ‡', 'Defensa'],
    ['SrÄ‘an BabiÄ‡', 'Defensa'],
    ['Nemanja MilunoviÄ‡', 'Defensa'],
    ['Filip MladenoviÄ‡', 'Defensa'],
    ['Nikola MilenkoviÄ‡', 'Defensa'],
    ['Sergej MilinkoviÄ‡-SaviÄ‡', 'Mediocampista'],
    ['Nemanja Gudelj', 'Mediocampista'],
    ['Ivan IliÄ‡', 'Mediocampista'],
    ['Filip KostiÄ‡', 'Mediocampista'],
    ['SaÅ¡a LukiÄ‡', 'Mediocampista'],
    ['Andrija Å½ivkoviÄ‡', 'Mediocampista'],
    ['DuÅ¡an VlahoviÄ‡', 'Delantero'],
    ['Luka JoviÄ‡', 'Delantero'],
    ['Aleksandar MitroviÄ‡', 'Delantero'],
  ]),
  makeTeam('ECU', 'Ecuador', 'ECU', 'E', false, [ // verificar grupo
    ['Luis LÃ³pez', 'Portero'],
    ['Harold Fonseca', 'Portero'],
    ['Marlon Licona', 'Portero'],
    ['Denil Maldonado', 'Defensa'],
    ['Marcelo Pereira', 'Defensa'],
    ['JosÃ© GarcÃ­a', 'Defensa'],
    ['Jonathan Rubio', 'Defensa'],
    ['Maynor Figueroa', 'Defensa'], // verificar
    ['Elvin Casildo', 'Defensa'],
    ['Bryan Moya', 'Mediocampista'],
    ['Deiby Flores', 'Mediocampista'],
    ['Luis Palma', 'Mediocampista'],
    ['Diego RodrÃ­guez', 'Mediocampista'], // verificar
    ['Kervin Arriaga', 'Mediocampista'],
    ['Edwin RodrÃ­guez', 'Mediocampista'], // verificar
    ['Romell Quioto', 'Delantero'],
    ['Alberth Elis', 'Delantero'],
    ['Cristian CÃ¡lix', 'Delantero'],
  ]),

  // â”€â”€ GRUPO F â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  makeTeam('NED', 'Países Bajos', 'NED', 'F', false, [
    ['Jasper Cillessen', 'Portero'],
    ['Remko Pasveer', 'Portero'],
    ['Mark Flekken', 'Portero'],
    ['Virgil van Dijk', 'Defensa'],
    ['Stefan de Vrij', 'Defensa'],
    ['Matthijs de Ligt', 'Defensa'],
    ['Denzel Dumfries', 'Defensa'],
    ['Daley Blind', 'Defensa'],
    ['Nathan AkÃ©', 'Defensa'],
    ['Frenkie de Jong', 'Mediocampista'],
    ['Georginio Wijnaldum', 'Mediocampista'],
    ['Teun Koopmeiners', 'Mediocampista'],
    ['Tijjani Reijnders', 'Mediocampista'],
    ['Xavi Simons', 'Mediocampista'],
    ['Davy Klaassen', 'Mediocampista'], // verificar
    ['Memphis Depay', 'Delantero'],
    ['Cody Gakpo', 'Delantero'],
    ['Donyell Malen', 'Delantero'],
  ]),
  makeTeam('JPN', 'Japón', 'JPN', 'F', false, [
    ['Kim Seung-gyu', 'Portero'],
    ['Cho Hyun-woo', 'Portero'],
    ['Song Bum-keun', 'Portero'],
    ['Kim Min-jae', 'Defensa'],
    ['Jung Seung-hyeon', 'Defensa'],
    ['Kim Jin-su', 'Defensa'],
    ['Hong Chul', 'Defensa'],
    ['Hwang In-beom', 'Defensa'], // verificar pos
    ['Cho Jin-woo', 'Defensa'], // verificar
    ['Lee Kang-in', 'Mediocampista'],
    ['Paik Seung-ho', 'Mediocampista'],
    ['Jung Woo-young', 'Mediocampista'],
    ['Jeong Sang-bin', 'Mediocampista'], // verificar
    ['Oh Hyeon-gyu', 'Mediocampista'], // verificar pos
    ['Yang Hyun-jun', 'Mediocampista'],
    ['Son Heung-min', 'Delantero'],
    ['Hwang Hee-chan', 'Delantero'],
    ['Cho Gue-sung', 'Delantero'],
  ]),
  makeTeam('SWE', 'Suecia', 'SWE', 'F', false, [
    ['Eloy Room', 'Portero'],
    ['Rainer Seip', 'Portero'],
    ['Averil Maynard', 'Portero'], // verificar
    ['Cuco Martina', 'Defensa'],
    ['Etienne Reijnen', 'Defensa'],
    ['Jair Marques', 'Defensa'],
    ['GregÃ³rio Neto', 'Defensa'],
    ['Neraldo Kartoredjo', 'Defensa'], // verificar
    ['Tjerk Boymans', 'Defensa'], // verificar
    ['Leandro Bacuna', 'Mediocampista'],
    ['Quentin Maciel', 'Mediocampista'],
    ['Giliano Wijnaldum', 'Mediocampista'],
    ['Genaro Gillet', 'Mediocampista'],
    ['Rangelo Janga', 'Mediocampista'],
    ['Jarchinio Antonia', 'Mediocampista'],
    ['Gino van Kessel', 'Delantero'],
    ['Jurich Carolina', 'Delantero'],
    ['CÃ©dric Willocx', 'Delantero'], // verificar
  ]),
  makeTeam('TUN', 'Túnez', 'TUN', 'F', false, [ // verificar grupo
    ['Ronwen Williams', 'Portero'],
    ['Ricardo Goss', 'Portero'],
    ['Veli Mothwa', 'Portero'],
    ['Siyanda Xulu', 'Defensa'],
    ['Rushine de Reuck', 'Defensa'],
    ['Nyiko Mobbie', 'Defensa'],
    ['Mothobi Mvala', 'Defensa'],
    ['Sifiso Hlanti', 'Defensa'],
    ['Aubrey Modiba', 'Defensa'],
    ['Teboho Mokoena', 'Mediocampista'],
    ['Yusuf Maart', 'Mediocampista'],
    ['Ethan Brooks', 'Mediocampista'],
    ['Themba Zwane', 'Mediocampista'],
    ['Bongani Zungu', 'Mediocampista'],
    ['Khuliso Mudau', 'Mediocampista'],
    ['Percy Tau', 'Delantero'],
    ['Lyle Foster', 'Delantero'],
    ['Evidence Makgopa', 'Delantero'],
  ]),

  // â”€â”€ GRUPO G â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  makeTeam('BEL', 'Bélgica', 'BEL', 'G', false, [
    ['Thibaut Courtois', 'Portero'],
    ['Simon Mignolet', 'Portero'],
    ['Koen Casteels', 'Portero'],
    ['Toby Alderweireld', 'Defensa'],
    ['Jan Vertonghen', 'Defensa'],
    ['Timothy Castagne', 'Defensa'],
    ['Zeno Debast', 'Defensa'],
    ['Thomas Meunier', 'Defensa'],
    ['Arthur Theate', 'Defensa'],
    ['Kevin De Bruyne', 'Mediocampista'],
    ['Youri Tielemans', 'Mediocampista'],
    ['Alexis Saelemaekers', 'Mediocampista'],
    ['Leandro Trossard', 'Mediocampista'],
    ['Charles De Ketelaere', 'Mediocampista'],
    ['Amadou Onana', 'Mediocampista'],
    ['Romelu Lukaku', 'Delantero'],
    ['Lois Openda', 'Delantero'],
    ['Dries Mertens', 'Delantero'],
  ]),
  makeTeam('EGV', 'Egipto', 'EGV', 'G', false, [
    ['Gianluigi Donnarumma', 'Portero'],
    ['Alex Meret', 'Portero'],
    ['Guglielmo Vicario', 'Portero'],
    ['Giovanni Di Lorenzo', 'Defensa'],
    ['Federico Dimarco', 'Defensa'],
    ['Alessandro Bastoni', 'Defensa'],
    ['Giorgio Scalvini', 'Defensa'],
    ['Leonardo Spinazzola', 'Defensa'],
    ['Destiny Udogie', 'Defensa'],
    ['NicolÃ² Barella', 'Mediocampista'],
    ['Jorginho', 'Mediocampista'],
    ['Lorenzo Pellegrini', 'Mediocampista'],
    ['Sandro Tonali', 'Mediocampista'],
    ['Bryan Cristante', 'Mediocampista'],
    ['Nicolo Fagioli', 'Mediocampista'], // verificar
    ['Federico Chiesa', 'Delantero'],
    ['Giacomo Raspadori', 'Delantero'],
    ['Mateo Retegui', 'Delantero'],
  ]),
  makeTeam('IRN', 'Irán', 'IRN', 'G', false, [ // verificar clasificaciÃ³n
    ['Carlos Lampe', 'Portero'],
    ['Guillermo Viscarra', 'Portero'],
    ['RubÃ©n Cordano', 'Portero'],
    ['JosÃ© Sagredo', 'Defensa'],
    ['Diego Bejarano', 'Defensa'],
    ['Marcelo SuÃ¡rez', 'Defensa'],
    ['Leonardo RamÃ­rez', 'Defensa'],
    ['Roberto FernÃ¡ndez', 'Defensa'],
    ['Luis HaquÃ­n', 'Defensa'],
    ['Ramiro Vaca', 'Mediocampista'],
    ['Henry Vaca', 'Mediocampista'],
    ['Erwin Saavedra', 'Mediocampista'],
    ['VÃ­ctor Abrego', 'Mediocampista'], // verificar
    ['Rodrigo Ramallo', 'Mediocampista'],
    ['Fernando Saucedo', 'Mediocampista'], // verificar
    ['Marcelo Moreno Martins', 'Delantero'],
    ['Bruno Miranda', 'Delantero'],
    ['Carmelo AlgaraÃ±az', 'Delantero'],
  ]),
  makeTeam('NZL', 'Nueva Zelanda', 'NZL', 'G', false, [
    ['Francis Uzoho', 'Portero'],
    ['Maduka Okoye', 'Portero'],
    ['Stanley Nwabali', 'Portero'],
    ['Calvin Bassey', 'Defensa'],
    ['William Troost-Ekong', 'Defensa'],
    ['Ola Aina', 'Defensa'],
    ['Chidozie Awaziem', 'Defensa'],
    ['Jamilu Collins', 'Defensa'],
    ['Semi Ajayi', 'Defensa'],
    ['Wilfred Ndidi', 'Mediocampista'],
    ['Alex Iwobi', 'Mediocampista'],
    ['Frank Onyeka', 'Mediocampista'],
    ['Joe Aribo', 'Mediocampista'],
    ['Dele-Bashiru', 'Mediocampista'], // verificar
    ['Ademola Lookman', 'Mediocampista'],
    ['Victor Osimhen', 'Delantero'],
    ['Kelechi Iheanacho', 'Delantero'],
    ['Samuel Chukwueze', 'Delantero'],
  ]),

  // â”€â”€ GRUPO H â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  makeTeam('ESP', 'España', 'ESP', 'H', false, [
    ['Unai SimÃ³n', 'Portero'],
    ['Robert SÃ¡nchez', 'Portero'],
    ['David Raya', 'Portero'],
    ['Dani Carvajal', 'Defensa'],
    ['Aymeric Laporte', 'Defensa'],
    ['Pau Torres', 'Defensa'],
    ['Alejandro Balde', 'Defensa'],
    ['Robin Le Normand', 'Defensa'],
    ['Nacho FernÃ¡ndez', 'Defensa'],
    ['Pedri', 'Mediocampista'],
    ['Gavi', 'Mediocampista'],
    ['Rodri', 'Mediocampista'],
    ['FabiÃ¡n Ruiz', 'Mediocampista'],
    ['Dani Olmo', 'Mediocampista'],
    ['Mikel Merino', 'Mediocampista'],
    ['Ãlvaro Morata', 'Delantero'],
    ['Ferran Torres', 'Delantero'],
    ['NicolÃ¡s Williams', 'Delantero'],
  ]),
  makeTeam('CPV', 'Cabo Verde', 'CPV', 'H', false, [
    ['Mert GÃ¼nok', 'Portero'],
    ['Altay BayÄ±ndÄ±r', 'Portero'],
    ['UÄŸurcan Ã‡akÄ±r', 'Portero'],
    ['Zeki Ã‡elik', 'Defensa'],
    ['Samet AkaydÄ±n', 'Defensa'],
    ['AbdÃ¼lkerim BardakcÄ±', 'Defensa'],
    ['Ferdi KadÄ±oÄŸlu', 'Defensa'],
    ['Mert MÃ¼ldÃ¼r', 'Defensa'],
    ['Kaan Ayhan', 'Defensa'],
    ['Hakan Ã‡alhanoÄŸlu', 'Mediocampista'],
    ['Arda GÃ¼ler', 'Mediocampista'],
    ['Salih Ã–zcan', 'Mediocampista'],
    ['Orkun KÃ¶kÃ§Ã¼', 'Mediocampista'],
    ['Ä°lkay GÃ¼ndoÄŸan', 'Mediocampista'], // verificar (dual nationality)
    ['BarÄ±ÅŸ Alper YÄ±lmaz', 'Mediocampista'],
    ['Kenan YÄ±ldÄ±z', 'Delantero'],
    ['Yusuf YazÄ±cÄ±', 'Delantero'],
    ['Cenk Tosun', 'Delantero'], // verificar
  ]),
  makeTeam('KSA', 'Arabia Saudita', 'KSA', 'H', false, [
    ['Antony Silva', 'Portero'],
    ['Alfredo Aguilar', 'Portero'],
    ['Rodrigo MuÃ±oz', 'Portero'],
    ['FabiÃ¡n Balbuena', 'Defensa'],
    ['Gustavo VelÃ¡zquez', 'Defensa'],
    ['Junior Alonso', 'Defensa'],
    ['Robert Rojas', 'Defensa'],
    ['Santiago Arzamendia', 'Defensa'],
    ['Blas Riveros', 'Defensa'],
    ['MathÃ­as Villasanti', 'Mediocampista'],
    ['GastÃ³n GimÃ©nez', 'Mediocampista'],
    ['Richard SÃ¡nchez', 'Mediocampista'],
    ['AndrÃ©s Cubas', 'Mediocampista'],
    ['Carlos GonzÃ¡lez', 'Mediocampista'],
    ['Ã“scar Romero', 'Mediocampista'],
    ['Miguel AlmirÃ³n', 'Delantero'],
    ['Braian Romero', 'Delantero'],
    ['Antonio Sanabria', 'Delantero'],
  ]),
  makeTeam('URU', 'Uruguay', 'URU', 'H', false, [
    ['Vozinha', 'Portero'],
    ['Brendan Rodrigues', 'Portero'],
    ['Ivanildo Casimiro', 'Portero'], // verificar
    ['Stopira', 'Defensa'],
    ['Jeffry Fortes', 'Defensa'],
    ['Steven Fortes', 'Defensa'],
    ['Diney', 'Defensa'],
    ['JoÃ£o Correia', 'Defensa'],
    ['Marco Moreno', 'Defensa'], // verificar
    ['Garry Rodrigues', 'Mediocampista'],
    ['Kenny Rocha', 'Mediocampista'],
    ['Ryan Mendes', 'Mediocampista'],
    ['Elinho', 'Mediocampista'],
    ['Patrick Andrade', 'Mediocampista'],
    ['Dylan Tavares', 'Mediocampista'], // verificar
    ['Djaniny', 'Delantero'],
    ['Jamiro Monteiro', 'Delantero'],
    ['FÃ¡bio Martins', 'Delantero'], // verificar
  ]),

  // â”€â”€ GRUPO I â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  makeTeam('FRA', 'Francia', 'FRA', 'I', false, [
    ['Mike Maignan', 'Portero'],
    ['Alphonse Areola', 'Portero'],
    ['Brice Samba', 'Portero'],
    ['ThÃ©o HernÃ¡ndez', 'Defensa'],
    ['Dayot Upamecano', 'Defensa'],
    ['William Saliba', 'Defensa'],
    ['Jules KoundÃ©', 'Defensa'],
    ['Ibrahima KonatÃ©', 'Defensa'],
    ['Benjamin Pavard', 'Defensa'],
    ['N\'Golo KantÃ©', 'Mediocampista'],
    ['AurÃ©lien TchouamÃ©ni', 'Mediocampista'],
    ['Eduardo Camavinga', 'Mediocampista'],
    ['Adrien Rabiot', 'Mediocampista'],
    ['Warren ZaÃ¯re-Emery', 'Mediocampista'],
    ['Kingsley Coman', 'Mediocampista'],
    ['Kylian MbappÃ©', 'Delantero'],
    ['Antoine Griezmann', 'Delantero'],
    ['Marcus Thuram', 'Delantero'],
  ]),
  makeTeam('SEN', 'Senegal', 'SEN', 'I', false, [
    ['Wojciech SzczÄ™sny', 'Portero'],
    ['Åukasz Skorupski', 'Portero'],
    ['BartÅ‚omiej DrÄ…gowski', 'Portero'],
    ['Matty Cash', 'Defensa'],
    ['Jan Bednarek', 'Defensa'],
    ['Kamil Glik', 'Defensa'], // verificar si sigue activo
    ['Bartosz BereszyÅ„ski', 'Defensa'],
    ['Robert Gumny', 'Defensa'],
    ['PaweÅ‚ Dawidowicz', 'Defensa'],
    ['Piotr ZieliÅ„ski', 'Mediocampista'],
    ['Mateusz Klich', 'Mediocampista'],
    ['Grzegorz Krychowiak', 'Mediocampista'], // verificar
    ['Szymon Å»urkowski', 'Mediocampista'],
    ['Sebastian SzymaÅ„ski', 'Mediocampista'],
    ['Nicola Zalewski', 'Mediocampista'],
    ['Robert Lewandowski', 'Delantero'],
    ['Arkadiusz Milik', 'Delantero'],
    ['Karol Åšwiderski', 'Delantero'],
  ]),
  makeTeam('IRQ', 'Irak', 'IRQ', 'I', false, [
    ['Amer Shafi', 'Portero'],
    ['Mohammad Abu Laban', 'Portero'],
    ['Mutaz Abu Ramaan', 'Portero'], // verificar
    ['Anas Bani Yaseen', 'Defensa'],
    ['Ehsan Haddad', 'Defensa'],
    ['Mahmoud Nasib', 'Defensa'],
    ['Yazid Abu Layla', 'Defensa'],
    ['Khaled Al-Rashdan', 'Defensa'],
    ['Mohammad Al-Dmeiri', 'Defensa'], // verificar
    ['Nour Al-Rawabdeh', 'Mediocampista'],
    ['Mahmoud Al-Mardi', 'Mediocampista'],
    ['Homam Ahmed', 'Mediocampista'],
    ['Yazan Naimat', 'Mediocampista'],
    ['Ahmad Saleh', 'Mediocampista'], // verificar
    ['Mousa Al-Tamari', 'Mediocampista'],
    ['Baha Faisal', 'Delantero'],
    ['Yazan Al-Arab', 'Delantero'],
    ['Abdallah Nasib', 'Delantero'], // verificar
  ]),
  makeTeam('NOR', 'Noruega', 'NOR', 'I', false, [ // verificar clasificaciÃ³n
    ['Craig Gordon', 'Portero'],
    ['Angus Gunn', 'Portero'],
    ['Zander Clark', 'Portero'],
    ['Andrew Robertson', 'Defensa'],
    ['Kieran Tierney', 'Defensa'],
    ['Grant Hanley', 'Defensa'],
    ['Anthony Ralston', 'Defensa'],
    ['Jack Hendry', 'Defensa'],
    ['Ryan Porteous', 'Defensa'],
    ['John McGinn', 'Mediocampista'],
    ['Callum McGregor', 'Mediocampista'],
    ['Stuart Armstrong', 'Mediocampista'],
    ['Ryan Christie', 'Mediocampista'],
    ['Scott McTominay', 'Mediocampista'],
    ['Billy Gilmour', 'Mediocampista'],
    ['Che Adams', 'Delantero'],
    ['Lyndon Dykes', 'Delantero'],
    ['Lawrence Shankland', 'Delantero'],
  ]),

  // â”€â”€ GRUPO J â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  makeTeam('ARG', 'Argentina', 'ARG', 'J', false, [
    ['Emiliano MartÃ­nez', 'Portero'],
    ['Franco Armani', 'Portero'],
    ['GerÃ³nimo Rulli', 'Portero'],
    ['Nahuel Molina', 'Defensa'],
    ['Lisandro MartÃ­nez', 'Defensa'],
    ['NicolÃ¡s Otamendi', 'Defensa'],
    ['Marcos AcuÃ±a', 'Defensa'],
    ['GermÃ¡n Pezzella', 'Defensa'],
    ['NicolÃ¡s Tagliafico', 'Defensa'],
    ['Rodrigo De Paul', 'Mediocampista'],
    ['Alexis Mac Allister', 'Mediocampista'],
    ['Enzo FernÃ¡ndez', 'Mediocampista'],
    ['Leandro Paredes', 'Mediocampista'],
    ['Giovani Lo Celso', 'Mediocampista'],
    ['NicolÃ¡s GonzÃ¡lez', 'Mediocampista'],
    ['Lionel Messi', 'Delantero'],
    ['Lautaro MartÃ­nez', 'Delantero'],
    ['JuliÃ¡n Ãlvarez', 'Delantero'],
  ]),
  makeTeam('ALG', 'Algeria', 'ALG', 'J', false, [ // verificar clasificaciÃ³n
    ['Andre Blake', 'Portero'],
    ['Jahmali Waite', 'Portero'],
    ['Dwayne Miller', 'Portero'],
    ['Damion Lowe', 'Defensa'],
    ['Kemar Lawrence', 'Defensa'],
    ['Joel Latibeaudiere', 'Defensa'],
    ['Javain Brown', 'Defensa'],
    ['Adrian Mariappa', 'Defensa'],
    ['Alvas Powell', 'Defensa'],
    ['Lamar Walker', 'Mediocampista'],
    ['Daniel Johnson', 'Mediocampista'],
    ['Shamar Nicholson', 'Mediocampista'],
    ['Jordon Ibe', 'Mediocampista'], // verificar
    ['Cory Burke', 'Mediocampista'],
    ['Ethan Pinnock', 'Mediocampista'], // verificar pos
    ['Leon Bailey', 'Delantero'],
    ['Michail Antonio', 'Delantero'],
    ['Bobby Decordova-Reid', 'Delantero'],
  ]),
  makeTeam('AUT', 'Austria', 'AUT', 'J', false, [ // verificar clasificaciÃ³n
    ['Keylor Navas', 'Portero'],
    ['Patrick Sequeira', 'Portero'],
    ['Esteban Alvarado', 'Portero'],
    ['Keysher Fuller', 'Defensa'],
    ['Francisco Calvo', 'Defensa'],
    ['Ã“scar Duarte', 'Defensa'],
    ['Ronald Matarrita', 'Defensa'],
    ['Juan Pablo Vargas', 'Defensa'],
    ['Ian Lawrence', 'Defensa'],
    ['Celso Borges', 'Mediocampista'],
    ['Yeltsin Tejeda', 'Mediocampista'],
    ['Bryan Ruiz', 'Mediocampista'], // verificar si sigue activo
    ['Douglas LÃ³pez', 'Mediocampista'],
    ['RÃ³nald Matarrita', 'Mediocampista'], // verificar
    ['Ãlvaro Zamora', 'Mediocampista'], // verificar
    ['Joel Campbell', 'Delantero'],
    ['Alonso MartÃ­nez', 'Delantero'],
    ['Anthony Contreras', 'Delantero'],
  ]),
  makeTeam('JOR', 'Jordania', 'JOR', 'J', false, [ // verificar clasificaciÃ³n
    ['Mohamed El-Shenawy', 'Portero'],
    ['Mohamed Abu Gabal', 'Portero'],
    ['Ahmed El-Shenawy', 'Portero'], // verificar
    ['Ahmed Hegazi', 'Defensa'],
    ['Mohamed Abdelmonem', 'Defensa'],
    ['Omar Gaber', 'Defensa'],
    ['Akram Tawfik', 'Defensa'],
    ['Mohamed Hamdy', 'Defensa'],
    ['Ayman Ashraf', 'Defensa'], // verificar
    ['Mohamed Elneny', 'Mediocampista'],
    ['Tarek Hamed', 'Mediocampista'],
    ['Amr El-Solia', 'Mediocampista'],
    ['Ahmed Sayed Zizo', 'Mediocampista'],
    ['Mahmoud Hassan Trezeguet', 'Mediocampista'],
    ['Emam Ashour', 'Mediocampista'], // verificar
    ['Mohamed Salah', 'Delantero'],
    ['Mostafa Mohamed', 'Delantero'],
    ['Omar Marmoush', 'Delantero'],
  ]),

  // â”€â”€ GRUPO K â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  makeTeam('POR', 'Portugal', 'POR', 'K', false, [
    ['Diogo Costa', 'Portero'],
    ['Rui PatrÃ­cio', 'Portero'],
    ['JosÃ© SÃ¡', 'Portero'],
    ['JoÃ£o Cancelo', 'Defensa'],
    ['RÃºben Dias', 'Defensa'],
    ['GonÃ§alo InÃ¡cio', 'Defensa'],
    ['Nuno Mendes', 'Defensa'],
    ['Diogo Dalot', 'Defensa'],
    ['AntÃ³nio Silva', 'Defensa'],
    ['Bernardo Silva', 'Mediocampista'],
    ['Bruno Fernandes', 'Mediocampista'],
    ['Vitinha', 'Mediocampista'],
    ['JoÃ£o FÃ©lix', 'Mediocampista'],
    ['OtÃ¡vio', 'Mediocampista'],
    ['Pedro Neto', 'Mediocampista'],
    ['Cristiano Ronaldo', 'Delantero'],
    ['GonÃ§alo Ramos', 'Delantero'],
    ['Rafael LeÃ£o', 'Delantero'],
  ]),
  makeTeam('COD', 'R.D. del Congo', 'COD', 'K', false, [
    ['Camilo Vargas', 'Portero'],
    ['Kevin Mier', 'Portero'],
    ['Ãlvaro Montero', 'Portero'],
    ['DÃ¡vinson SÃ¡nchez', 'Defensa'],
    ['Yerry Mina', 'Defensa'],
    ['Daniel MuÃ±oz', 'Defensa'],
    ['Jhon LucumÃ­', 'Defensa'],
    ['Johan Mojica', 'Defensa'],
    ['Carlos Cuesta', 'Defensa'],
    ['James RodrÃ­guez', 'Mediocampista'],
    ['Mateus Uribe', 'Mediocampista'],
    ['Jefferson Lerma', 'Mediocampista'],
    ['Richard RÃ­os', 'Mediocampista'],
    ['Jhon Arias', 'Mediocampista'],
    ['Juan Fernando Quintero', 'Mediocampista'],
    ['Luis DÃ­az', 'Delantero'],
    ['Jhon DurÃ¡n', 'Delantero'],
    ['Cucho HernÃ¡ndez', 'Delantero'],
  ]),
  makeTeam('UZB', 'Uzbekistán', 'UZB', 'K', false, [
    ['Otabek Suyunov', 'Portero'],
    ['Abduvohid Nematov', 'Portero'],
    ['Jasur Yaxshiboev', 'Portero'], // verificar
    ['Shokhrukh Norchayev', 'Defensa'],
    ['Akramjon Komilov', 'Defensa'],
    ['Abdukodir Khusanov', 'Defensa'],
    ['Khurshid Tursunov', 'Defensa'],
    ['Nodir Tursunov', 'Defensa'], // verificar
    ['Dostonbek Tursunov', 'Defensa'], // verificar
    ['Otabek Shukurov', 'Mediocampista'],
    ['Jaloliddin Masharipov', 'Mediocampista'],
    ['Azizbek Turgunboev', 'Mediocampista'],
    ['Lochinbek Abdukholiqov', 'Mediocampista'], // verificar
    ['Jamshid Iskanderov', 'Mediocampista'], // verificar
    ['Humoyun Murodov', 'Mediocampista'], // verificar
    ['Eldor Shomurodov', 'Delantero'],
    ['Dostonbek Khamdamov', 'Delantero'],
    ['Avazbek Nazarov', 'Delantero'], // verificar
  ]),
  makeTeam('COL', 'Colombia', 'COL', 'K', false, [
    ['JoÃ«l Kiassumbua', 'Portero'],
    ['Lionel Mpasi', 'Portero'],
    ['Ley Matampi', 'Portero'], // verificar
    ['Arthur Masuaku', 'Defensa'],
    ['Chancel Mbemba', 'Defensa'],
    ['Mechack JÃ©rÃ´me', 'Defensa'],
    ['Dylan Lokosa', 'Defensa'], // verificar
    ['Merveille Bope', 'Defensa'], // verificar
    ['Marcel Tisserand', 'Defensa'],
    ['Neeskens Kebano', 'Mediocampista'],
    ['GaÃ«l Kakuta', 'Mediocampista'],
    ['Jean-Marc Makusu', 'Mediocampista'], // verificar
    ['Arnold Bouka Moutou', 'Mediocampista'],
    ['Yannick Bolasie', 'Mediocampista'],
    ['CÃ©dric Bakambu', 'Mediocampista'],
    ['Silas Wamangituka', 'Delantero'],
    ['HÃ©ritier Luvumbu', 'Delantero'],
    ['Meschak Elia', 'Delantero'], // verificar
  ]),

  // â”€â”€ GRUPO L â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  makeTeam('ENG', 'Inglaterra', 'ENG', 'L', false, [
    ['Jordan Pickford', 'Portero'],
    ['Aaron Ramsdale', 'Portero'],
    ['Sam Johnstone', 'Portero'],
    ['Trent Alexander-Arnold', 'Defensa'],
    ['Harry Maguire', 'Defensa'],
    ['John Stones', 'Defensa'],
    ['Marc Guehi', 'Defensa'],
    ['Ben Chilwell', 'Defensa'],
    ['Levi Colwill', 'Defensa'],
    ['Declan Rice', 'Mediocampista'],
    ['Jude Bellingham', 'Mediocampista'],
    ['Phil Foden', 'Mediocampista'],
    ['Bukayo Saka', 'Mediocampista'],
    ['Conor Gallagher', 'Mediocampista'],
    ['Curtis Jones', 'Mediocampista'],
    ['Harry Kane', 'Delantero'],
    ['Marcus Rashford', 'Delantero'],
    ['Ollie Watkins', 'Delantero'],
  ]),
  makeTeam('CRO', 'Croacia', 'CRO', 'L', false, [
    ['Kasper Schmeichel', 'Portero'],
    ['Oliver Christensen', 'Portero'],
    ['Frederik RÃ¸nnow', 'Portero'],
    ['Joakim Andersen', 'Defensa'],
    ['Andreas Christensen', 'Defensa'],
    ['Victor Nelsson', 'Defensa'],
    ['Rasmus Kristensen', 'Defensa'],
    ['Alexander Bah', 'Defensa'],
    ['Jens Stryger Larsen', 'Defensa'],
    ['Christian Eriksen', 'Mediocampista'],
    ['Pierre-Emile HÃ¸jbjerg', 'Mediocampista'],
    ['Thomas Delaney', 'Mediocampista'],
    ['Mikkel Damsgaard', 'Mediocampista'],
    ['Mathias Jensen', 'Mediocampista'],
    ['Andreas Skov Olsen', 'Mediocampista'],
    ['Rasmus HÃ¸jlund', 'Delantero'],
    ['Yussuf Poulsen', 'Delantero'],
    ['Jonas Wind', 'Delantero'],
  ]),
  makeTeam('GHA', 'Ghana', 'GHA', 'L', false, [
    ['Fernando Muslera', 'Portero'],
    ['Sergio Rochet', 'Portero'],
    ['SebastiÃ¡n Sosa', 'Portero'],
    ['JosÃ© MarÃ­a GimÃ©nez', 'Defensa'],
    ['Ronald AraÃºjo', 'Defensa'],
    ['Nahitan NÃ¡ndez', 'Defensa'],
    ['Marcelo Saracchi', 'Defensa'],
    ['SebastiÃ¡n CÃ¡ceres', 'Defensa'],
    ['MathÃ­as Olivera', 'Defensa'],
    ['Federico Valverde', 'Mediocampista'],
    ['Lucas Torreira', 'Mediocampista'],
    ['Rodrigo Bentancur', 'Mediocampista'],
    ['MatÃ­as Vecino', 'Mediocampista'],
    ['Manuel Ugarte', 'Mediocampista'],
    ['Facundo Pellistri', 'Mediocampista'],
    ['Darwin NÃºÃ±ez', 'Delantero'],
    ['Facundo Torres', 'Delantero'],
    ['Maxi GÃ³mez', 'Delantero'],
  ]),
  makeTeam('PAN', 'Panamá', 'PAN', 'L', false, [ // verificar clasificaciÃ³n
    ['Jalal Hassan', 'Portero'],
    ['Mohammed Hameed', 'Portero'],
    ['Fahad Talib', 'Portero'], // verificar
    ['Ali Adnan', 'Defensa'],
    ['Rebin Sulaka', 'Defensa'],
    ['Hussein Saber', 'Defensa'],
    ['Ahmed Ibrahim', 'Defensa'],
    ['Saman Qurizagh', 'Defensa'],
    ['Mustafa Nadhim', 'Defensa'], // verificar
    ['Amjed Attwan', 'Mediocampista'],
    ['Safaa Hadi', 'Mediocampista'],
    ['Mohannad Ali', 'Mediocampista'],
    ['Amjed Kalaf', 'Mediocampista'], // verificar
    ['Bashar Resan', 'Mediocampista'],
    ['Hussein Falah', 'Mediocampista'], // verificar
    ['Aymen Hussein', 'Delantero'],
    ['Emad Mohammed', 'Delantero'],
    ['Ahmed Yasin', 'Delantero'],
  ]),
];

// Ãndice de equipos por cÃ³digo
const TEAMS = {};
TEAMS_DATA.forEach(t => { TEAMS[t.code] = t; });
ADDITIONAL_SECTIONS.forEach(t => { TEAMS[t.code] = t; });

// Grupos ordenados
const GROUPS = {
  A: ['MEX', 'RSA', 'KOR', 'CZE'],
  B: ['CAN', 'BIH', 'QAT', 'SUI'],
  C: ['BRA', 'MAR', 'HAI', 'SCO'],
  D: ['USA', 'PAR', 'AUS', 'TUR'],
  E: ['GER', 'CUW', 'CIV', 'ECU'],
  F: ['NED', 'JPN', 'SWE', 'TUN'],
  G: ['BEL', 'EGV', 'IRN', 'NZL'],
  H: ['ESP', 'CPV', 'KSA', 'URU'],
  I: ['FRA', 'SEN', 'IRQ', 'NOR'],
  J: ['ARG', 'ALG', 'AUT', 'JOR'],
  K: ['POR', 'COD', 'UZB', 'COL'],
  L: ['ENG', 'CRO', 'GHA', 'PAN'],
};

const TOTAL_BASE = 994;
const TOTAL_TEAMS_STICKERS = 960; // 48 Ã— 20
const TOTAL_ADDITIONAL_STICKERS = ADDITIONAL_SECTIONS.reduce((sum, section) => sum + section.stickers.length, 0);
const TOTAL_ALBUM_STICKERS = TOTAL_TEAMS_STICKERS + TOTAL_ADDITIONAL_STICKERS;
const TOTAL_SPECIAL = ADDITIONAL_SECTIONS[0].stickers.length;
const TOTAL_EXTRA = 22;
const STICKERS_PER_PACK = 7;


