// ============================================================
// DATA.JS — Álbum Panini Mundial 2026
// NOTA: Grupos basados en el sorteo oficial FIFA (5 dic 2024).
// Jugadores según convocatorias más recientes. Marcar // verificar
// donde hay incertidumbre. Actualiza este archivo si hay cambios.
// ============================================================

const POSITIONS = { POR: 'Portero', DEF: 'Defensa', MED: 'Mediocampista', DEL: 'Delantero' };

const SPECIAL_STICKERS = [
  { code: 'SEC-01', name: 'Presentación del torneo' },
  { code: 'SEC-02', name: 'Historia del Mundial' },
  { code: 'SEC-03', name: 'Mascota oficial' },
  { code: 'SEC-04', name: 'Balón oficial' },
  { code: 'SEC-05', name: 'Trofeo FIFA' },
  { code: 'SEC-06', name: 'Estadio AT&T (Arlington)' },
  { code: 'SEC-07', name: 'Estadio Rose Bowl (LA)' },
  { code: 'SEC-08', name: 'Estadio MetLife (NJ)' },
  { code: 'SEC-09', name: 'Estadio Levi\'s (SF)' },
  { code: 'SEC-10', name: 'Estadio Arrowhead (KC)' },
  { code: 'SEC-11', name: 'Estadio Lincoln Financial (Phil)' },
  { code: 'SEC-12', name: 'Estadio Gillette (Boston)' },
  { code: 'SEC-13', name: 'Estadio NRG (Houston)' },
  { code: 'SEC-14', name: 'Estadio Allegiant (LV)' },
  { code: 'SEC-15', name: 'Estadio Seattle' },
  { code: 'SEC-16', name: 'Estadio BC Place (Vancouver)' },
  { code: 'SEC-17', name: 'Estadio Azteca (Ciudad de México)' },
  { code: 'SEC-18', name: 'Estadio Estadio BBVA (Monterrey)' },
  { code: 'SEC-19', name: 'Calendario de partidos' },
  { code: 'SEC-20', name: 'Sede y organizadores' },
];

const EXTRA_STICKERS = [
  // Dorados (7)
  { code: 'EXT-G01', name: 'Lionel Messi', team: 'ARG', variant: 'gold' },
  { code: 'EXT-G02', name: 'Kylian Mbappé', team: 'FRA', variant: 'gold' },
  { code: 'EXT-G03', name: 'Erling Haaland', team: 'NOR', variant: 'gold' }, // verificar
  { code: 'EXT-G04', name: 'Vinícius Jr.', team: 'BRA', variant: 'gold' },
  { code: 'EXT-G05', name: 'Jude Bellingham', team: 'ENG', variant: 'gold' },
  { code: 'EXT-G06', name: 'Cristiano Ronaldo', team: 'POR', variant: 'gold' },
  { code: 'EXT-G07', name: 'Lautaro Martínez', team: 'ARG', variant: 'gold' },
  // Plateados (8)
  { code: 'EXT-S01', name: 'Son Heung-min', team: 'KOR', variant: 'silver' },
  { code: 'EXT-S02', name: 'Mohamed Salah', team: 'EGY', variant: 'silver' },
  { code: 'EXT-S03', name: 'Kevin De Bruyne', team: 'BEL', variant: 'silver' },
  { code: 'EXT-S04', name: 'Harry Kane', team: 'ENG', variant: 'silver' },
  { code: 'EXT-S05', name: 'Rodri', team: 'ESP', variant: 'silver' },
  { code: 'EXT-S06', name: 'Pedri', team: 'ESP', variant: 'silver' },
  { code: 'EXT-S07', name: 'Florian Wirtz', team: 'GER', variant: 'silver' },
  { code: 'EXT-S08', name: 'Bukayo Saka', team: 'ENG', variant: 'silver' },
  // Bronce (7)
  { code: 'EXT-B01', name: 'Luis Díaz', team: 'COL', variant: 'bronze' },
  { code: 'EXT-B02', name: 'Darwin Núñez', team: 'URU', variant: 'bronze' },
  { code: 'EXT-B03', name: 'Victor Osimhen', team: 'NGA', variant: 'bronze' },
  { code: 'EXT-B04', name: 'Takefusa Kubo', team: 'JPN', variant: 'bronze' },
  { code: 'EXT-B05', name: 'Frenkie de Jong', team: 'NED', variant: 'bronze' },
  { code: 'EXT-B06', name: 'Gavi', team: 'ESP', variant: 'bronze' },
  { code: 'EXT-B07', name: 'Federico Valverde', team: 'URU', variant: 'bronze' },
];

const ADDITIONAL_SECTIONS = [
  {
    code: 'FWC',
    name: 'FIFA World Cup',
    icon: 'FWC',
    group: 'Especiales',
    stickers: [
      { code: '00', name: 'Lamina 00', type: 'album-special' },
      ...[
        'FWC1', 'FWC2', 'FWC3', 'FWC4', 'FWC5', 'FWC6', 'FWC7', 'FWC8', 'FWC9',
        'FWC10', 'FWC11', 'FWC12', 'FWC13', 'FWC14', 'FWC15', 'FWC16', 'FWC17', 'FWC18', 'FWC19'
      ].map(code => ({ code, name: code, type: 'album-special' }))
    ]
  },
  {
    code: 'CC',
    name: 'Coca-Cola',
    icon: 'CC',
    group: 'Coca-Cola',
    stickers: [
      'CC1', 'CC2', 'CC3', 'CC4', 'CC5', 'CC6', 'CC7',
      'CC8', 'CC9', 'CC10', 'CC11', 'CC12', 'CC13', 'CC14'
    ].map(code => ({ code, name: code, type: 'sponsor' }))
  }
];

// Helper para generar stickers de un equipo
function makeTeam(code, name, flag, group, debutant, players) {
  return {
    code, name, flag, group, debutant,
    stickers: [
      { code: `${code}-01`, name: 'Escudo oficial', type: 'shield' },
      { code: `${code}-02`, name: 'Foto grupal', type: 'group' },
      ...players.map((p, i) => ({
        code: `${code}-${String(i + 3).padStart(2, '0')}`,
        name: p[0],
        position: p[1],
        type: 'player'
      }))
    ]
  };
}

const TEAMS_DATA = [
  // ── GRUPO A ──────────────────────────────────────────────
  makeTeam('MEX', 'México', '🇲🇽', 'A', false, [
    ['Guillermo Ochoa', 'Portero'],
    ['Luis Malagón', 'Portero'],
    ['Rodolfo Cota', 'Portero'],
    ['Jorge Sánchez', 'Defensa'],
    ['César Montes', 'Defensa'],
    ['Johan Vásquez', 'Defensa'],
    ['Gerardo Arteaga', 'Defensa'],
    ['Julián Araújo', 'Defensa'],
    ['Jorge Moreno', 'Defensa'], // verificar
    ['Edson Álvarez', 'Mediocampista'],
    ['Carlos Rodríguez', 'Mediocampista'],
    ['Orbelín Pineda', 'Mediocampista'],
    ['Roberto Alvarado', 'Mediocampista'],
    ['Luis Romo', 'Mediocampista'], // verificar
    ['Érick Gutiérrez', 'Mediocampista'], // verificar
    ['Hirving Lozano', 'Delantero'],
    ['Henry Martín', 'Delantero'],
    ['Santiago Giménez', 'Delantero'],
  ]),
  makeTeam('ECU', 'Ecuador', '🇪🇨', 'A', false, [
    ['Hernán Galíndez', 'Portero'],
    ['Alexander Domínguez', 'Portero'],
    ['Wellington Ramírez', 'Portero'], // verificar
    ['Piero Hincapié', 'Defensa'],
    ['Byron Castillo', 'Defensa'],
    ['Pervis Estupiñán', 'Defensa'],
    ['Jackson Porozo', 'Defensa'],
    ['Diego Palacios', 'Defensa'],
    ['Félix Torres', 'Defensa'],
    ['Carlos Gruezo', 'Mediocampista'],
    ['Moisés Caicedo', 'Mediocampista'],
    ['Jhegson Méndez', 'Mediocampista'],
    ['Ángel Mena', 'Mediocampista'],
    ['Jeremy Sarmiento', 'Mediocampista'],
    ['Gonzalo Plata', 'Mediocampista'],
    ['Enner Valencia', 'Delantero'],
    ['Michael Estrada', 'Delantero'],
    ['Jordy Caicedo', 'Delantero'], // verificar
  ]),
  makeTeam('SEN', 'Senegal', '🇸🇳', 'A', false, [
    ['Édouard Mendy', 'Portero'],
    ['Sény Dieng', 'Portero'],
    ['Alfred Gomis', 'Portero'],
    ['Kalidou Koulibaly', 'Defensa'],
    ['Abdou Diallo', 'Defensa'],
    ['Fodé Ballo-Touré', 'Defensa'],
    ['Youssouf Sabaly', 'Defensa'],
    ['Moussa Niakhaté', 'Defensa'],
    ['Formose Mendy', 'Defensa'], // verificar
    ['Cheikhou Kouyaté', 'Mediocampista'],
    ['Nampalys Mendy', 'Mediocampista'],
    ['Pape Gueye', 'Mediocampista'],
    ['Krepin Diatta', 'Mediocampista'],
    ['Pathé Ciss', 'Mediocampista'],
    ['Lamine Camara', 'Mediocampista'], // verificar
    ['Sadio Mané', 'Delantero'],
    ['Ismaïla Sarr', 'Delantero'],
    ['Habib Diallo', 'Delantero'],
  ]),
  makeTeam('ROU', 'Rumanía', '🇷🇴', 'A', false, [ // verificar grupo
    ['Florin Niță', 'Portero'],
    ['Horațiu Moldovan', 'Portero'],
    ['Ștefan Târnovanu', 'Portero'],
    ['Andrei Rațiu', 'Defensa'],
    ['Radu Drăgușin', 'Defensa'],
    ['Cristian Manea', 'Defensa'],
    ['Adrian Rus', 'Defensa'],
    ['Ionuț Nedelcearu', 'Defensa'],
    ['Bogdan Racovițan', 'Defensa'],
    ['Razvan Marin', 'Mediocampista'],
    ['Deian Sorescu', 'Mediocampista'],
    ['Nicușor Bancu', 'Mediocampista'],
    ['Octavian Popescu', 'Mediocampista'],
    ['Dennis Man', 'Mediocampista'],
    ['Alexandru Ioniță', 'Mediocampista'], // verificar
    ['Denis Alibec', 'Delantero'],
    ['Florinel Coman', 'Delantero'],
    ['George Pușcaș', 'Delantero'],
  ]),

  // ── GRUPO B ──────────────────────────────────────────────
  makeTeam('CAN', 'Canadá', '🇨🇦', 'B', false, [
    ['Maxime Crépeau', 'Portero'],
    ['Milan Borjan', 'Portero'],
    ['James Pantemis', 'Portero'],
    ['Alistair Johnston', 'Defensa'],
    ['Kamal Miller', 'Defensa'],
    ['Doneil Henry', 'Defensa'],
    ['Derek Cornelius', 'Defensa'],
    ['Scott Kennedy', 'Defensa'],
    ['Richie Laryea', 'Defensa'],
    ['Atiba Hutchinson', 'Mediocampista'],
    ['Stephen Eustáquio', 'Mediocampista'],
    ['Jonathan Osorio', 'Mediocampista'],
    ['Samuel Piette', 'Mediocampista'],
    ['Mark-Anthony Kaye', 'Mediocampista'],
    ['Liam Millar', 'Mediocampista'], // verificar
    ['Alphonso Davies', 'Delantero'],
    ['Jonathan David', 'Delantero'],
    ['Cyle Larin', 'Delantero'],
  ]),
  makeTeam('MAR', 'Marruecos', '🇲🇦', 'B', false, [
    ['Yassine Bounou', 'Portero'],
    ['Munir Mohamedi', 'Portero'],
    ['Ahmed Tagnaouti', 'Portero'],
    ['Noussair Mazraoui', 'Defensa'],
    ['Achraf Hakimi', 'Defensa'],
    ['Romain Saïss', 'Defensa'],
    ['Nayef Aguerd', 'Defensa'],
    ['Jawad El-Yamiq', 'Defensa'],
    ['Adam Masina', 'Defensa'],
    ['Azzedine Ounahi', 'Mediocampista'],
    ['Sofyan Amrabat', 'Mediocampista'],
    ['Selim Amallah', 'Mediocampista'],
    ['Ilias Chair', 'Mediocampista'],
    ['Bilal El Khannouss', 'Mediocampista'],
    ['Abde Ezzalzouli', 'Mediocampista'],
    ['Hakim Ziyech', 'Delantero'],
    ['Youssef En-Nesyri', 'Delantero'],
    ['Soufiane Boufal', 'Delantero'],
  ]),
  makeTeam('CRO', 'Croacia', '🇭🇷', 'B', false, [
    ['Dominik Livaković', 'Portero'],
    ['Ivo Grbić', 'Portero'],
    ['Nedeljko Labrović', 'Portero'],
    ['Josip Šutalo', 'Defensa'],
    ['Duje Ćaleta-Car', 'Defensa'],
    ['Joško Gvardiol', 'Defensa'],
    ['Borna Sosa', 'Defensa'],
    ['Josip Juranović', 'Defensa'],
    ['Domagoj Vida', 'Defensa'], // verificar
    ['Luka Modrić', 'Mediocampista'],
    ['Marcelo Brozović', 'Mediocampista'],
    ['Mateo Kovačić', 'Mediocampista'],
    ['Mario Pašalić', 'Mediocampista'],
    ['Lovro Majer', 'Mediocampista'],
    ['Luka Sučić', 'Mediocampista'],
    ['Ante Budimir', 'Delantero'],
    ['Ivan Perišić', 'Delantero'],
    ['Andrej Kramarić', 'Delantero'],
  ]),
  makeTeam('PAN', 'Panamá', '🇵🇦', 'B', false, [
    ['Luis Mejía', 'Portero'],
    ['Orlando Mosquera', 'Portero'],
    ['Gianluca Cariolato', 'Portero'],
    ['Michael Murillo', 'Defensa'],
    ['Harold Cummings', 'Defensa'],
    ['Fidel Escobar', 'Defensa'],
    ['Eric Davis', 'Defensa'],
    ['Roderick Miller', 'Defensa'],
    ['Andrés Andrade', 'Defensa'],
    ['Adalberto Carrasquilla', 'Mediocampista'],
    ['Alberto Quintero', 'Mediocampista'],
    ['Aníbal Godoy', 'Mediocampista'],
    ['Edgar Bárcenas', 'Mediocampista'],
    ['Álex Rodríguez', 'Mediocampista'], // verificar
    ['Abdiel Ayarza', 'Mediocampista'], // verificar
    ['Ismael Díaz', 'Delantero'],
    ['Cecilio Waterman', 'Delantero'],
    ['José Fajardo', 'Delantero'],
  ]),

  // ── GRUPO C ──────────────────────────────────────────────
  makeTeam('BRA', 'Brasil', '🇧🇷', 'C', false, [
    ['Alisson', 'Portero'],
    ['Éderson', 'Portero'],
    ['Weverton', 'Portero'],
    ['Danilo', 'Defensa'],
    ['Éder Militão', 'Defensa'],
    ['Marquinhos', 'Defensa'],
    ['Gabriel Magalhães', 'Defensa'],
    ['Guilherme Arana', 'Defensa'],
    ['Alex Sandro', 'Defensa'], // verificar
    ['Casemiro', 'Mediocampista'],
    ['Bruno Guimarães', 'Mediocampista'],
    ['Lucas Paquetá', 'Mediocampista'],
    ['Raphinha', 'Mediocampista'],
    ['Rodrygo', 'Mediocampista'],
    ['Gerson', 'Mediocampista'],
    ['Vinícius Jr.', 'Delantero'],
    ['Endrick', 'Delantero'],
    ['Gabriel Martinelli', 'Delantero'],
  ]),
  makeTeam('JPN', 'Japón', '🇯🇵', 'C', false, [
    ['Shuichi Gonda', 'Portero'],
    ['Daniel Schmidt', 'Portero'],
    ['Zion Suzuki', 'Portero'],
    ['Hiroki Sakai', 'Defensa'],
    ['Maya Yoshida', 'Defensa'],
    ['Ko Itakura', 'Defensa'],
    ['Shogo Taniguchi', 'Defensa'],
    ['Yuto Nagatomo', 'Defensa'],
    ['Miki Yamane', 'Defensa'],
    ['Wataru Endō', 'Mediocampista'],
    ['Hidemasa Morita', 'Mediocampista'],
    ['Junya Ito', 'Mediocampista'],
    ['Takefusa Kubo', 'Mediocampista'],
    ['Kaoru Mitoma', 'Mediocampista'],
    ['Daichi Kamada', 'Mediocampista'],
    ['Ritsu Doan', 'Delantero'],
    ['Ayase Ueda', 'Delantero'],
    ['Shuto Machino', 'Delantero'], // verificar
  ]),
  makeTeam('CMR', 'Camerún', '🇨🇲', 'C', false, [
    ['André Onana', 'Portero'],
    ['Devis Epassy', 'Portero'],
    ['Simon Ngapandouetnbu', 'Portero'],
    ['Collins Fai', 'Defensa'],
    ['Ambroise Oyongo', 'Defensa'],
    ['Jean-Charles Castelletto', 'Defensa'],
    ['Enzo Tchato', 'Defensa'],
    ['Olivier Mbaizo', 'Defensa'],
    ['Christopher Wooh', 'Defensa'],
    ['Martin Hongla', 'Mediocampista'],
    ['André Zambo Anguissa', 'Mediocampista'],
    ['Samuel Gouet', 'Mediocampista'],
    ['Gaël Ondoua', 'Mediocampista'], // verificar
    ['Pierre Kunde', 'Mediocampista'],
    ['Olivier Ntcham', 'Mediocampista'], // verificar
    ['Vincent Aboubakar', 'Delantero'],
    ['Karl Toko Ekambi', 'Delantero'],
    ['Bryan Mbeumo', 'Delantero'],
  ]),
  makeTeam('NZL', 'Nueva Zelanda', '🇳🇿', 'C', false, [ // verificar grupo
    ['Stefan Marinovic', 'Portero'],
    ['Michael Woud', 'Portero'],
    ['Max Crocombe', 'Portero'],
    ['Michael Boxall', 'Defensa'],
    ['Winston Reid', 'Defensa'],
    ['Liberato Cacace', 'Defensa'],
    ['Nando de Wys', 'Defensa'],
    ['Elijah Just', 'Defensa'],
    ['Louis Fenton', 'Defensa'], // verificar
    ['Joe Bell', 'Mediocampista'],
    ['Clayton Lewis', 'Mediocampista'],
    ['Callum McCowatt', 'Mediocampista'],
    ['Garbhan Coughlan', 'Mediocampista'], // verificar
    ['Kosta Barbarouses', 'Mediocampista'],
    ['Ryan Thomas', 'Mediocampista'],
    ['Chris Wood', 'Delantero'],
    ['Matthew Garbett', 'Delantero'],
    ['Dane Ingham', 'Delantero'], // verificar
  ]),

  // ── GRUPO D ──────────────────────────────────────────────
  makeTeam('USA', 'Estados Unidos', '🇺🇸', 'D', false, [
    ['Matt Turner', 'Portero'],
    ['Ethan Horvath', 'Portero'],
    ['Gabriel Slonina', 'Portero'],
    ['Sergiño Dest', 'Defensa'],
    ['Tim Ream', 'Defensa'],
    ['Chris Richards', 'Defensa'],
    ['Miles Robinson', 'Defensa'],
    ['Joe Scally', 'Defensa'],
    ['Antonee Robinson', 'Defensa'],
    ['Tyler Adams', 'Mediocampista'],
    ['Weston McKennie', 'Mediocampista'],
    ['Yunus Musah', 'Mediocampista'],
    ['Luca de la Torre', 'Mediocampista'],
    ['Gio Reyna', 'Mediocampista'],
    ['Brenden Aaronson', 'Mediocampista'],
    ['Christian Pulisic', 'Delantero'],
    ['Josh Sargent', 'Delantero'],
    ['Folarin Balogun', 'Delantero'],
  ]),
  makeTeam('KSA', 'Arabia Saudita', '🇸🇦', 'D', false, [
    ['Mohammed Al-Owais', 'Portero'],
    ['Nawaf Al-Aqidi', 'Portero'],
    ['Yasser Al-Mosailem', 'Portero'],
    ['Saud Abdulhamid', 'Defensa'],
    ['Ali Al-Bulaihi', 'Defensa'],
    ['Hassan Tambakti', 'Defensa'],
    ['Abdulellah Al-Amri', 'Defensa'],
    ['Abdullah Madu', 'Defensa'],
    ['Sultan Al-Ghannam', 'Defensa'], // verificar
    ['Salman Al-Faraj', 'Mediocampista'],
    ['Mohammed Kanno', 'Mediocampista'],
    ['Nasser Al-Dawsari', 'Mediocampista'],
    ['Riyadh Sharahili', 'Mediocampista'],
    ['Sami Al-Najei', 'Mediocampista'], // verificar
    ['Hattan Bahbri', 'Mediocampista'], // verificar
    ['Salem Al-Dawsari', 'Delantero'],
    ['Firas Al-Buraikan', 'Delantero'],
    ['Abdullah Al-Hamdan', 'Delantero'],
  ]),
  makeTeam('SUI', 'Suiza', '🇨🇭', 'D', false, [
    ['Yann Sommer', 'Portero'],
    ['Gregor Kobel', 'Portero'],
    ['Philipp Köhn', 'Portero'],
    ['Manuel Akanji', 'Defensa'],
    ['Nico Elvedi', 'Defensa'],
    ['Fabian Schär', 'Defensa'],
    ['Ricardo Rodríguez', 'Defensa'],
    ['Silvan Widmer', 'Defensa'],
    ['Kevin Mbabu', 'Defensa'],
    ['Granit Xhaka', 'Mediocampista'],
    ['Remo Freuler', 'Mediocampista'],
    ['Michel Aebischer', 'Mediocampista'],
    ['Xherdan Shaqiri', 'Mediocampista'],
    ['Fabian Frei', 'Mediocampista'], // verificar
    ['Dan Ndoye', 'Mediocampista'],
    ['Breel Embolo', 'Delantero'],
    ['Noah Okafor', 'Delantero'],
    ['Haris Seferović', 'Delantero'],
  ]),
  makeTeam('GHA', 'Ghana', '🇬🇭', 'D', false, [
    ['Lawrence Ati-Zigi', 'Portero'],
    ['Ibrahim Danlad', 'Portero'],
    ['Joe Wollacott', 'Portero'],
    ['Alexander Djiku', 'Defensa'],
    ['Daniel Amartey', 'Defensa'],
    ['Mohammed Salisu', 'Defensa'],
    ['Tariq Lamptey', 'Defensa'],
    ['Dennis Odoi', 'Defensa'],
    ['Baba Abdul Rahman', 'Defensa'],
    ['Thomas Partey', 'Mediocampista'],
    ['Idrissu Baba', 'Mediocampista'],
    ['André Ayew', 'Mediocampista'],
    ['Salis Abdul Samed', 'Mediocampista'],
    ['Osman Bukari', 'Mediocampista'],
    ['Jordan Ayew', 'Mediocampista'],
    ['Inaki Williams', 'Delantero'],
    ['Antoine Semenyo', 'Delantero'],
    ['Kamaldeen Sulemana', 'Delantero'],
  ]),

  // ── GRUPO E ──────────────────────────────────────────────
  makeTeam('GER', 'Alemania', '🇩🇪', 'E', false, [
    ['Manuel Neuer', 'Portero'],
    ['Marc-André ter Stegen', 'Portero'],
    ['Oliver Baumann', 'Portero'],
    ['Joshua Kimmich', 'Defensa'],
    ['Antonio Rüdiger', 'Defensa'],
    ['Jonathan Tah', 'Defensa'],
    ['David Raum', 'Defensa'],
    ['Thilo Kehrer', 'Defensa'],
    ['Benjamin Henrichs', 'Defensa'],
    ['Ilkay Gündoğan', 'Mediocampista'],
    ['Leon Goretzka', 'Mediocampista'],
    ['Florian Wirtz', 'Mediocampista'],
    ['Jamal Musiala', 'Mediocampista'],
    ['Thomas Müller', 'Mediocampista'],
    ['Kai Havertz', 'Mediocampista'],
    ['Leroy Sané', 'Delantero'],
    ['Serge Gnabry', 'Delantero'],
    ['Niclas Füllkrug', 'Delantero'],
  ]),
  makeTeam('AUS', 'Australia', '🇦🇺', 'E', false, [
    ['Mathew Ryan', 'Portero'],
    ['Danny Vukovic', 'Portero'],
    ['Joe Gauci', 'Portero'],
    ['Miloš Degenek', 'Defensa'],
    ['Harry Souttar', 'Defensa'],
    ['Aziz Behich', 'Defensa'],
    ['Jason Davidson', 'Defensa'],
    ['Nathaniel Atkinson', 'Defensa'],
    ['Fran Karacic', 'Defensa'], // verificar
    ['Aaron Mooy', 'Mediocampista'],
    ['Jackson Irvine', 'Mediocampista'],
    ['Riley McGree', 'Mediocampista'],
    ['Ajdin Hrustic', 'Mediocampista'],
    ['Cameron Devlin', 'Mediocampista'],
    ['Connor Metcalfe', 'Mediocampista'], // verificar
    ['Mathew Leckie', 'Delantero'],
    ['Mitchell Duke', 'Delantero'],
    ['Martin Boyle', 'Delantero'],
  ]),
  makeTeam('SRB', 'Serbia', '🇷🇸', 'E', false, [
    ['Predrag Rajković', 'Portero'],
    ['Vanja Milinković-Savić', 'Portero'],
    ['Marko Dmitrović', 'Portero'],
    ['Strahinja Pavlović', 'Defensa'],
    ['Miloš Veljković', 'Defensa'],
    ['Srđan Babić', 'Defensa'],
    ['Nemanja Milunović', 'Defensa'],
    ['Filip Mladenović', 'Defensa'],
    ['Nikola Milenković', 'Defensa'],
    ['Sergej Milinković-Savić', 'Mediocampista'],
    ['Nemanja Gudelj', 'Mediocampista'],
    ['Ivan Ilić', 'Mediocampista'],
    ['Filip Kostić', 'Mediocampista'],
    ['Saša Lukić', 'Mediocampista'],
    ['Andrija Živković', 'Mediocampista'],
    ['Dušan Vlahović', 'Delantero'],
    ['Luka Jović', 'Delantero'],
    ['Aleksandar Mitrović', 'Delantero'],
  ]),
  makeTeam('HON', 'Honduras', '🇭🇳', 'E', false, [ // verificar grupo
    ['Luis López', 'Portero'],
    ['Harold Fonseca', 'Portero'],
    ['Marlon Licona', 'Portero'],
    ['Denil Maldonado', 'Defensa'],
    ['Marcelo Pereira', 'Defensa'],
    ['José García', 'Defensa'],
    ['Jonathan Rubio', 'Defensa'],
    ['Maynor Figueroa', 'Defensa'], // verificar
    ['Elvin Casildo', 'Defensa'],
    ['Bryan Moya', 'Mediocampista'],
    ['Deiby Flores', 'Mediocampista'],
    ['Luis Palma', 'Mediocampista'],
    ['Diego Rodríguez', 'Mediocampista'], // verificar
    ['Kervin Arriaga', 'Mediocampista'],
    ['Edwin Rodríguez', 'Mediocampista'], // verificar
    ['Romell Quioto', 'Delantero'],
    ['Alberth Elis', 'Delantero'],
    ['Cristian Cálix', 'Delantero'],
  ]),

  // ── GRUPO F ──────────────────────────────────────────────
  makeTeam('NED', 'Países Bajos', '🇳🇱', 'F', false, [
    ['Jasper Cillessen', 'Portero'],
    ['Remko Pasveer', 'Portero'],
    ['Mark Flekken', 'Portero'],
    ['Virgil van Dijk', 'Defensa'],
    ['Stefan de Vrij', 'Defensa'],
    ['Matthijs de Ligt', 'Defensa'],
    ['Denzel Dumfries', 'Defensa'],
    ['Daley Blind', 'Defensa'],
    ['Nathan Aké', 'Defensa'],
    ['Frenkie de Jong', 'Mediocampista'],
    ['Georginio Wijnaldum', 'Mediocampista'],
    ['Teun Koopmeiners', 'Mediocampista'],
    ['Tijjani Reijnders', 'Mediocampista'],
    ['Xavi Simons', 'Mediocampista'],
    ['Davy Klaassen', 'Mediocampista'], // verificar
    ['Memphis Depay', 'Delantero'],
    ['Cody Gakpo', 'Delantero'],
    ['Donyell Malen', 'Delantero'],
  ]),
  makeTeam('KOR', 'Corea del Sur', '🇰🇷', 'F', false, [
    ['Kim Seung-gyu', 'Portero'],
    ['Cho Hyun-woo', 'Portero'],
    ['Song Bum-keun', 'Portero'],
    ['Kim Min-jae', 'Defensa'],
    ['Jung Seung-hyeon', 'Defensa'],
    ['Kim Jin-su', 'Defensa'],
    ['Hong Chul', 'Defensa'],
    ['Hwang In-beom', 'Defensa'], // verificar pos
    ['Cho Jin-woo', 'Defensa'], // verificar
    ['Lee Kang-in', 'Mediocampista'],
    ['Paik Seung-ho', 'Mediocampista'],
    ['Jung Woo-young', 'Mediocampista'],
    ['Jeong Sang-bin', 'Mediocampista'], // verificar
    ['Oh Hyeon-gyu', 'Mediocampista'], // verificar pos
    ['Yang Hyun-jun', 'Mediocampista'],
    ['Son Heung-min', 'Delantero'],
    ['Hwang Hee-chan', 'Delantero'],
    ['Cho Gue-sung', 'Delantero'],
  ]),
  makeTeam('CUW', 'Curazao', '🇨🇼', 'F', true, [
    ['Eloy Room', 'Portero'],
    ['Rainer Seip', 'Portero'],
    ['Averil Maynard', 'Portero'], // verificar
    ['Cuco Martina', 'Defensa'],
    ['Etienne Reijnen', 'Defensa'],
    ['Jair Marques', 'Defensa'],
    ['Gregório Neto', 'Defensa'],
    ['Neraldo Kartoredjo', 'Defensa'], // verificar
    ['Tjerk Boymans', 'Defensa'], // verificar
    ['Leandro Bacuna', 'Mediocampista'],
    ['Quentin Maciel', 'Mediocampista'],
    ['Giliano Wijnaldum', 'Mediocampista'],
    ['Genaro Gillet', 'Mediocampista'],
    ['Rangelo Janga', 'Mediocampista'],
    ['Jarchinio Antonia', 'Mediocampista'],
    ['Gino van Kessel', 'Delantero'],
    ['Jurich Carolina', 'Delantero'],
    ['Cédric Willocx', 'Delantero'], // verificar
  ]),
  makeTeam('RSA', 'Sudáfrica', '🇿🇦', 'F', false, [ // verificar grupo
    ['Ronwen Williams', 'Portero'],
    ['Ricardo Goss', 'Portero'],
    ['Veli Mothwa', 'Portero'],
    ['Siyanda Xulu', 'Defensa'],
    ['Rushine de Reuck', 'Defensa'],
    ['Nyiko Mobbie', 'Defensa'],
    ['Mothobi Mvala', 'Defensa'],
    ['Sifiso Hlanti', 'Defensa'],
    ['Aubrey Modiba', 'Defensa'],
    ['Teboho Mokoena', 'Mediocampista'],
    ['Yusuf Maart', 'Mediocampista'],
    ['Ethan Brooks', 'Mediocampista'],
    ['Themba Zwane', 'Mediocampista'],
    ['Bongani Zungu', 'Mediocampista'],
    ['Khuliso Mudau', 'Mediocampista'],
    ['Percy Tau', 'Delantero'],
    ['Lyle Foster', 'Delantero'],
    ['Evidence Makgopa', 'Delantero'],
  ]),

  // ── GRUPO G ──────────────────────────────────────────────
  makeTeam('BEL', 'Bélgica', '🇧🇪', 'G', false, [
    ['Thibaut Courtois', 'Portero'],
    ['Simon Mignolet', 'Portero'],
    ['Koen Casteels', 'Portero'],
    ['Toby Alderweireld', 'Defensa'],
    ['Jan Vertonghen', 'Defensa'],
    ['Timothy Castagne', 'Defensa'],
    ['Zeno Debast', 'Defensa'],
    ['Thomas Meunier', 'Defensa'],
    ['Arthur Theate', 'Defensa'],
    ['Kevin De Bruyne', 'Mediocampista'],
    ['Youri Tielemans', 'Mediocampista'],
    ['Alexis Saelemaekers', 'Mediocampista'],
    ['Leandro Trossard', 'Mediocampista'],
    ['Charles De Ketelaere', 'Mediocampista'],
    ['Amadou Onana', 'Mediocampista'],
    ['Romelu Lukaku', 'Delantero'],
    ['Lois Openda', 'Delantero'],
    ['Dries Mertens', 'Delantero'],
  ]),
  makeTeam('ITA', 'Italia', '🇮🇹', 'G', false, [
    ['Gianluigi Donnarumma', 'Portero'],
    ['Alex Meret', 'Portero'],
    ['Guglielmo Vicario', 'Portero'],
    ['Giovanni Di Lorenzo', 'Defensa'],
    ['Federico Dimarco', 'Defensa'],
    ['Alessandro Bastoni', 'Defensa'],
    ['Giorgio Scalvini', 'Defensa'],
    ['Leonardo Spinazzola', 'Defensa'],
    ['Destiny Udogie', 'Defensa'],
    ['Nicolò Barella', 'Mediocampista'],
    ['Jorginho', 'Mediocampista'],
    ['Lorenzo Pellegrini', 'Mediocampista'],
    ['Sandro Tonali', 'Mediocampista'],
    ['Bryan Cristante', 'Mediocampista'],
    ['Nicolo Fagioli', 'Mediocampista'], // verificar
    ['Federico Chiesa', 'Delantero'],
    ['Giacomo Raspadori', 'Delantero'],
    ['Mateo Retegui', 'Delantero'],
  ]),
  makeTeam('BOL', 'Bolivia', '🇧🇴', 'G', false, [ // verificar clasificación
    ['Carlos Lampe', 'Portero'],
    ['Guillermo Viscarra', 'Portero'],
    ['Rubén Cordano', 'Portero'],
    ['José Sagredo', 'Defensa'],
    ['Diego Bejarano', 'Defensa'],
    ['Marcelo Suárez', 'Defensa'],
    ['Leonardo Ramírez', 'Defensa'],
    ['Roberto Fernández', 'Defensa'],
    ['Luis Haquín', 'Defensa'],
    ['Ramiro Vaca', 'Mediocampista'],
    ['Henry Vaca', 'Mediocampista'],
    ['Erwin Saavedra', 'Mediocampista'],
    ['Víctor Abrego', 'Mediocampista'], // verificar
    ['Rodrigo Ramallo', 'Mediocampista'],
    ['Fernando Saucedo', 'Mediocampista'], // verificar
    ['Marcelo Moreno Martins', 'Delantero'],
    ['Bruno Miranda', 'Delantero'],
    ['Carmelo Algarañaz', 'Delantero'],
  ]),
  makeTeam('NGA', 'Nigeria', '🇳🇬', 'G', false, [
    ['Francis Uzoho', 'Portero'],
    ['Maduka Okoye', 'Portero'],
    ['Stanley Nwabali', 'Portero'],
    ['Calvin Bassey', 'Defensa'],
    ['William Troost-Ekong', 'Defensa'],
    ['Ola Aina', 'Defensa'],
    ['Chidozie Awaziem', 'Defensa'],
    ['Jamilu Collins', 'Defensa'],
    ['Semi Ajayi', 'Defensa'],
    ['Wilfred Ndidi', 'Mediocampista'],
    ['Alex Iwobi', 'Mediocampista'],
    ['Frank Onyeka', 'Mediocampista'],
    ['Joe Aribo', 'Mediocampista'],
    ['Dele-Bashiru', 'Mediocampista'], // verificar
    ['Ademola Lookman', 'Mediocampista'],
    ['Victor Osimhen', 'Delantero'],
    ['Kelechi Iheanacho', 'Delantero'],
    ['Samuel Chukwueze', 'Delantero'],
  ]),

  // ── GRUPO H ──────────────────────────────────────────────
  makeTeam('ESP', 'España', '🇪🇸', 'H', false, [
    ['Unai Simón', 'Portero'],
    ['Robert Sánchez', 'Portero'],
    ['David Raya', 'Portero'],
    ['Dani Carvajal', 'Defensa'],
    ['Aymeric Laporte', 'Defensa'],
    ['Pau Torres', 'Defensa'],
    ['Alejandro Balde', 'Defensa'],
    ['Robin Le Normand', 'Defensa'],
    ['Nacho Fernández', 'Defensa'],
    ['Pedri', 'Mediocampista'],
    ['Gavi', 'Mediocampista'],
    ['Rodri', 'Mediocampista'],
    ['Fabián Ruiz', 'Mediocampista'],
    ['Dani Olmo', 'Mediocampista'],
    ['Mikel Merino', 'Mediocampista'],
    ['Álvaro Morata', 'Delantero'],
    ['Ferran Torres', 'Delantero'],
    ['Nicolás Williams', 'Delantero'],
  ]),
  makeTeam('TUR', 'Turquía', '🇹🇷', 'H', false, [
    ['Mert Günok', 'Portero'],
    ['Altay Bayındır', 'Portero'],
    ['Uğurcan Çakır', 'Portero'],
    ['Zeki Çelik', 'Defensa'],
    ['Samet Akaydın', 'Defensa'],
    ['Abdülkerim Bardakcı', 'Defensa'],
    ['Ferdi Kadıoğlu', 'Defensa'],
    ['Mert Müldür', 'Defensa'],
    ['Kaan Ayhan', 'Defensa'],
    ['Hakan Çalhanoğlu', 'Mediocampista'],
    ['Arda Güler', 'Mediocampista'],
    ['Salih Özcan', 'Mediocampista'],
    ['Orkun Kökçü', 'Mediocampista'],
    ['İlkay Gündoğan', 'Mediocampista'], // verificar (dual nationality)
    ['Barış Alper Yılmaz', 'Mediocampista'],
    ['Kenan Yıldız', 'Delantero'],
    ['Yusuf Yazıcı', 'Delantero'],
    ['Cenk Tosun', 'Delantero'], // verificar
  ]),
  makeTeam('PAR', 'Paraguay', '🇵🇾', 'H', false, [
    ['Antony Silva', 'Portero'],
    ['Alfredo Aguilar', 'Portero'],
    ['Rodrigo Muñoz', 'Portero'],
    ['Fabián Balbuena', 'Defensa'],
    ['Gustavo Velázquez', 'Defensa'],
    ['Junior Alonso', 'Defensa'],
    ['Robert Rojas', 'Defensa'],
    ['Santiago Arzamendia', 'Defensa'],
    ['Blas Riveros', 'Defensa'],
    ['Mathías Villasanti', 'Mediocampista'],
    ['Gastón Giménez', 'Mediocampista'],
    ['Richard Sánchez', 'Mediocampista'],
    ['Andrés Cubas', 'Mediocampista'],
    ['Carlos González', 'Mediocampista'],
    ['Óscar Romero', 'Mediocampista'],
    ['Miguel Almirón', 'Delantero'],
    ['Braian Romero', 'Delantero'],
    ['Antonio Sanabria', 'Delantero'],
  ]),
  makeTeam('CPV', 'Cabo Verde', '🇨🇻', 'H', true, [
    ['Vozinha', 'Portero'],
    ['Brendan Rodrigues', 'Portero'],
    ['Ivanildo Casimiro', 'Portero'], // verificar
    ['Stopira', 'Defensa'],
    ['Jeffry Fortes', 'Defensa'],
    ['Steven Fortes', 'Defensa'],
    ['Diney', 'Defensa'],
    ['João Correia', 'Defensa'],
    ['Marco Moreno', 'Defensa'], // verificar
    ['Garry Rodrigues', 'Mediocampista'],
    ['Kenny Rocha', 'Mediocampista'],
    ['Ryan Mendes', 'Mediocampista'],
    ['Elinho', 'Mediocampista'],
    ['Patrick Andrade', 'Mediocampista'],
    ['Dylan Tavares', 'Mediocampista'], // verificar
    ['Djaniny', 'Delantero'],
    ['Jamiro Monteiro', 'Delantero'],
    ['Fábio Martins', 'Delantero'], // verificar
  ]),

  // ── GRUPO I ──────────────────────────────────────────────
  makeTeam('FRA', 'Francia', '🇫🇷', 'I', false, [
    ['Mike Maignan', 'Portero'],
    ['Alphonse Areola', 'Portero'],
    ['Brice Samba', 'Portero'],
    ['Théo Hernández', 'Defensa'],
    ['Dayot Upamecano', 'Defensa'],
    ['William Saliba', 'Defensa'],
    ['Jules Koundé', 'Defensa'],
    ['Ibrahima Konaté', 'Defensa'],
    ['Benjamin Pavard', 'Defensa'],
    ['N\'Golo Kanté', 'Mediocampista'],
    ['Aurélien Tchouaméni', 'Mediocampista'],
    ['Eduardo Camavinga', 'Mediocampista'],
    ['Adrien Rabiot', 'Mediocampista'],
    ['Warren Zaïre-Emery', 'Mediocampista'],
    ['Kingsley Coman', 'Mediocampista'],
    ['Kylian Mbappé', 'Delantero'],
    ['Antoine Griezmann', 'Delantero'],
    ['Marcus Thuram', 'Delantero'],
  ]),
  makeTeam('POL', 'Polonia', '🇵🇱', 'I', false, [
    ['Wojciech Szczęsny', 'Portero'],
    ['Łukasz Skorupski', 'Portero'],
    ['Bartłomiej Drągowski', 'Portero'],
    ['Matty Cash', 'Defensa'],
    ['Jan Bednarek', 'Defensa'],
    ['Kamil Glik', 'Defensa'], // verificar si sigue activo
    ['Bartosz Bereszyński', 'Defensa'],
    ['Robert Gumny', 'Defensa'],
    ['Paweł Dawidowicz', 'Defensa'],
    ['Piotr Zieliński', 'Mediocampista'],
    ['Mateusz Klich', 'Mediocampista'],
    ['Grzegorz Krychowiak', 'Mediocampista'], // verificar
    ['Szymon Żurkowski', 'Mediocampista'],
    ['Sebastian Szymański', 'Mediocampista'],
    ['Nicola Zalewski', 'Mediocampista'],
    ['Robert Lewandowski', 'Delantero'],
    ['Arkadiusz Milik', 'Delantero'],
    ['Karol Świderski', 'Delantero'],
  ]),
  makeTeam('JOR', 'Jordania', '🇯🇴', 'I', true, [
    ['Amer Shafi', 'Portero'],
    ['Mohammad Abu Laban', 'Portero'],
    ['Mutaz Abu Ramaan', 'Portero'], // verificar
    ['Anas Bani Yaseen', 'Defensa'],
    ['Ehsan Haddad', 'Defensa'],
    ['Mahmoud Nasib', 'Defensa'],
    ['Yazid Abu Layla', 'Defensa'],
    ['Khaled Al-Rashdan', 'Defensa'],
    ['Mohammad Al-Dmeiri', 'Defensa'], // verificar
    ['Nour Al-Rawabdeh', 'Mediocampista'],
    ['Mahmoud Al-Mardi', 'Mediocampista'],
    ['Homam Ahmed', 'Mediocampista'],
    ['Yazan Naimat', 'Mediocampista'],
    ['Ahmad Saleh', 'Mediocampista'], // verificar
    ['Mousa Al-Tamari', 'Mediocampista'],
    ['Baha Faisal', 'Delantero'],
    ['Yazan Al-Arab', 'Delantero'],
    ['Abdallah Nasib', 'Delantero'], // verificar
  ]),
  makeTeam('SCO', 'Escocia', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'I', false, [ // verificar clasificación
    ['Craig Gordon', 'Portero'],
    ['Angus Gunn', 'Portero'],
    ['Zander Clark', 'Portero'],
    ['Andrew Robertson', 'Defensa'],
    ['Kieran Tierney', 'Defensa'],
    ['Grant Hanley', 'Defensa'],
    ['Anthony Ralston', 'Defensa'],
    ['Jack Hendry', 'Defensa'],
    ['Ryan Porteous', 'Defensa'],
    ['John McGinn', 'Mediocampista'],
    ['Callum McGregor', 'Mediocampista'],
    ['Stuart Armstrong', 'Mediocampista'],
    ['Ryan Christie', 'Mediocampista'],
    ['Scott McTominay', 'Mediocampista'],
    ['Billy Gilmour', 'Mediocampista'],
    ['Che Adams', 'Delantero'],
    ['Lyndon Dykes', 'Delantero'],
    ['Lawrence Shankland', 'Delantero'],
  ]),

  // ── GRUPO J ──────────────────────────────────────────────
  makeTeam('ARG', 'Argentina', '🇦🇷', 'J', false, [
    ['Emiliano Martínez', 'Portero'],
    ['Franco Armani', 'Portero'],
    ['Gerónimo Rulli', 'Portero'],
    ['Nahuel Molina', 'Defensa'],
    ['Lisandro Martínez', 'Defensa'],
    ['Nicolás Otamendi', 'Defensa'],
    ['Marcos Acuña', 'Defensa'],
    ['Germán Pezzella', 'Defensa'],
    ['Nicolás Tagliafico', 'Defensa'],
    ['Rodrigo De Paul', 'Mediocampista'],
    ['Alexis Mac Allister', 'Mediocampista'],
    ['Enzo Fernández', 'Mediocampista'],
    ['Leandro Paredes', 'Mediocampista'],
    ['Giovani Lo Celso', 'Mediocampista'],
    ['Nicolás González', 'Mediocampista'],
    ['Lionel Messi', 'Delantero'],
    ['Lautaro Martínez', 'Delantero'],
    ['Julián Álvarez', 'Delantero'],
  ]),
  makeTeam('JAM', 'Jamaica', '🇯🇲', 'J', false, [ // verificar clasificación
    ['Andre Blake', 'Portero'],
    ['Jahmali Waite', 'Portero'],
    ['Dwayne Miller', 'Portero'],
    ['Damion Lowe', 'Defensa'],
    ['Kemar Lawrence', 'Defensa'],
    ['Joel Latibeaudiere', 'Defensa'],
    ['Javain Brown', 'Defensa'],
    ['Adrian Mariappa', 'Defensa'],
    ['Alvas Powell', 'Defensa'],
    ['Lamar Walker', 'Mediocampista'],
    ['Daniel Johnson', 'Mediocampista'],
    ['Shamar Nicholson', 'Mediocampista'],
    ['Jordon Ibe', 'Mediocampista'], // verificar
    ['Cory Burke', 'Mediocampista'],
    ['Ethan Pinnock', 'Mediocampista'], // verificar pos
    ['Leon Bailey', 'Delantero'],
    ['Michail Antonio', 'Delantero'],
    ['Bobby Decordova-Reid', 'Delantero'],
  ]),
  makeTeam('CRC', 'Costa Rica', '🇨🇷', 'J', false, [ // verificar clasificación
    ['Keylor Navas', 'Portero'],
    ['Patrick Sequeira', 'Portero'],
    ['Esteban Alvarado', 'Portero'],
    ['Keysher Fuller', 'Defensa'],
    ['Francisco Calvo', 'Defensa'],
    ['Óscar Duarte', 'Defensa'],
    ['Ronald Matarrita', 'Defensa'],
    ['Juan Pablo Vargas', 'Defensa'],
    ['Ian Lawrence', 'Defensa'],
    ['Celso Borges', 'Mediocampista'],
    ['Yeltsin Tejeda', 'Mediocampista'],
    ['Bryan Ruiz', 'Mediocampista'], // verificar si sigue activo
    ['Douglas López', 'Mediocampista'],
    ['Rónald Matarrita', 'Mediocampista'], // verificar
    ['Álvaro Zamora', 'Mediocampista'], // verificar
    ['Joel Campbell', 'Delantero'],
    ['Alonso Martínez', 'Delantero'],
    ['Anthony Contreras', 'Delantero'],
  ]),
  makeTeam('EGY', 'Egipto', '🇪🇬', 'J', false, [ // verificar clasificación
    ['Mohamed El-Shenawy', 'Portero'],
    ['Mohamed Abu Gabal', 'Portero'],
    ['Ahmed El-Shenawy', 'Portero'], // verificar
    ['Ahmed Hegazi', 'Defensa'],
    ['Mohamed Abdelmonem', 'Defensa'],
    ['Omar Gaber', 'Defensa'],
    ['Akram Tawfik', 'Defensa'],
    ['Mohamed Hamdy', 'Defensa'],
    ['Ayman Ashraf', 'Defensa'], // verificar
    ['Mohamed Elneny', 'Mediocampista'],
    ['Tarek Hamed', 'Mediocampista'],
    ['Amr El-Solia', 'Mediocampista'],
    ['Ahmed Sayed Zizo', 'Mediocampista'],
    ['Mahmoud Hassan Trezeguet', 'Mediocampista'],
    ['Emam Ashour', 'Mediocampista'], // verificar
    ['Mohamed Salah', 'Delantero'],
    ['Mostafa Mohamed', 'Delantero'],
    ['Omar Marmoush', 'Delantero'],
  ]),

  // ── GRUPO K ──────────────────────────────────────────────
  makeTeam('POR', 'Portugal', '🇵🇹', 'K', false, [
    ['Diogo Costa', 'Portero'],
    ['Rui Patrício', 'Portero'],
    ['José Sá', 'Portero'],
    ['João Cancelo', 'Defensa'],
    ['Rúben Dias', 'Defensa'],
    ['Gonçalo Inácio', 'Defensa'],
    ['Nuno Mendes', 'Defensa'],
    ['Diogo Dalot', 'Defensa'],
    ['António Silva', 'Defensa'],
    ['Bernardo Silva', 'Mediocampista'],
    ['Bruno Fernandes', 'Mediocampista'],
    ['Vitinha', 'Mediocampista'],
    ['João Félix', 'Mediocampista'],
    ['Otávio', 'Mediocampista'],
    ['Pedro Neto', 'Mediocampista'],
    ['Cristiano Ronaldo', 'Delantero'],
    ['Gonçalo Ramos', 'Delantero'],
    ['Rafael Leão', 'Delantero'],
  ]),
  makeTeam('COL', 'Colombia', '🇨🇴', 'K', false, [
    ['Camilo Vargas', 'Portero'],
    ['Kevin Mier', 'Portero'],
    ['Álvaro Montero', 'Portero'],
    ['Dávinson Sánchez', 'Defensa'],
    ['Yerry Mina', 'Defensa'],
    ['Daniel Muñoz', 'Defensa'],
    ['Jhon Lucumí', 'Defensa'],
    ['Johan Mojica', 'Defensa'],
    ['Carlos Cuesta', 'Defensa'],
    ['James Rodríguez', 'Mediocampista'],
    ['Mateus Uribe', 'Mediocampista'],
    ['Jefferson Lerma', 'Mediocampista'],
    ['Richard Ríos', 'Mediocampista'],
    ['Jhon Arias', 'Mediocampista'],
    ['Juan Fernando Quintero', 'Mediocampista'],
    ['Luis Díaz', 'Delantero'],
    ['Jhon Durán', 'Delantero'],
    ['Cucho Hernández', 'Delantero'],
  ]),
  makeTeam('UZB', 'Uzbekistán', '🇺🇿', 'K', true, [
    ['Otabek Suyunov', 'Portero'],
    ['Abduvohid Nematov', 'Portero'],
    ['Jasur Yaxshiboev', 'Portero'], // verificar
    ['Shokhrukh Norchayev', 'Defensa'],
    ['Akramjon Komilov', 'Defensa'],
    ['Abdukodir Khusanov', 'Defensa'],
    ['Khurshid Tursunov', 'Defensa'],
    ['Nodir Tursunov', 'Defensa'], // verificar
    ['Dostonbek Tursunov', 'Defensa'], // verificar
    ['Otabek Shukurov', 'Mediocampista'],
    ['Jaloliddin Masharipov', 'Mediocampista'],
    ['Azizbek Turgunboev', 'Mediocampista'],
    ['Lochinbek Abdukholiqov', 'Mediocampista'], // verificar
    ['Jamshid Iskanderov', 'Mediocampista'], // verificar
    ['Humoyun Murodov', 'Mediocampista'], // verificar
    ['Eldor Shomurodov', 'Delantero'],
    ['Dostonbek Khamdamov', 'Delantero'],
    ['Avazbek Nazarov', 'Delantero'], // verificar
  ]),
  makeTeam('COD', 'R.D. del Congo', '🇨🇩', 'K', false, [
    ['Joël Kiassumbua', 'Portero'],
    ['Lionel Mpasi', 'Portero'],
    ['Ley Matampi', 'Portero'], // verificar
    ['Arthur Masuaku', 'Defensa'],
    ['Chancel Mbemba', 'Defensa'],
    ['Mechack Jérôme', 'Defensa'],
    ['Dylan Lokosa', 'Defensa'], // verificar
    ['Merveille Bope', 'Defensa'], // verificar
    ['Marcel Tisserand', 'Defensa'],
    ['Neeskens Kebano', 'Mediocampista'],
    ['Gaël Kakuta', 'Mediocampista'],
    ['Jean-Marc Makusu', 'Mediocampista'], // verificar
    ['Arnold Bouka Moutou', 'Mediocampista'],
    ['Yannick Bolasie', 'Mediocampista'],
    ['Cédric Bakambu', 'Mediocampista'],
    ['Silas Wamangituka', 'Delantero'],
    ['Héritier Luvumbu', 'Delantero'],
    ['Meschak Elia', 'Delantero'], // verificar
  ]),

  // ── GRUPO L ──────────────────────────────────────────────
  makeTeam('ENG', 'Inglaterra', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'L', false, [
    ['Jordan Pickford', 'Portero'],
    ['Aaron Ramsdale', 'Portero'],
    ['Sam Johnstone', 'Portero'],
    ['Trent Alexander-Arnold', 'Defensa'],
    ['Harry Maguire', 'Defensa'],
    ['John Stones', 'Defensa'],
    ['Marc Guehi', 'Defensa'],
    ['Ben Chilwell', 'Defensa'],
    ['Levi Colwill', 'Defensa'],
    ['Declan Rice', 'Mediocampista'],
    ['Jude Bellingham', 'Mediocampista'],
    ['Phil Foden', 'Mediocampista'],
    ['Bukayo Saka', 'Mediocampista'],
    ['Conor Gallagher', 'Mediocampista'],
    ['Curtis Jones', 'Mediocampista'],
    ['Harry Kane', 'Delantero'],
    ['Marcus Rashford', 'Delantero'],
    ['Ollie Watkins', 'Delantero'],
  ]),
  makeTeam('DEN', 'Dinamarca', '🇩🇰', 'L', false, [
    ['Kasper Schmeichel', 'Portero'],
    ['Oliver Christensen', 'Portero'],
    ['Frederik Rønnow', 'Portero'],
    ['Joakim Andersen', 'Defensa'],
    ['Andreas Christensen', 'Defensa'],
    ['Victor Nelsson', 'Defensa'],
    ['Rasmus Kristensen', 'Defensa'],
    ['Alexander Bah', 'Defensa'],
    ['Jens Stryger Larsen', 'Defensa'],
    ['Christian Eriksen', 'Mediocampista'],
    ['Pierre-Emile Højbjerg', 'Mediocampista'],
    ['Thomas Delaney', 'Mediocampista'],
    ['Mikkel Damsgaard', 'Mediocampista'],
    ['Mathias Jensen', 'Mediocampista'],
    ['Andreas Skov Olsen', 'Mediocampista'],
    ['Rasmus Højlund', 'Delantero'],
    ['Yussuf Poulsen', 'Delantero'],
    ['Jonas Wind', 'Delantero'],
  ]),
  makeTeam('URU', 'Uruguay', '🇺🇾', 'L', false, [
    ['Fernando Muslera', 'Portero'],
    ['Sergio Rochet', 'Portero'],
    ['Sebastián Sosa', 'Portero'],
    ['José María Giménez', 'Defensa'],
    ['Ronald Araújo', 'Defensa'],
    ['Nahitan Nández', 'Defensa'],
    ['Marcelo Saracchi', 'Defensa'],
    ['Sebastián Cáceres', 'Defensa'],
    ['Mathías Olivera', 'Defensa'],
    ['Federico Valverde', 'Mediocampista'],
    ['Lucas Torreira', 'Mediocampista'],
    ['Rodrigo Bentancur', 'Mediocampista'],
    ['Matías Vecino', 'Mediocampista'],
    ['Manuel Ugarte', 'Mediocampista'],
    ['Facundo Pellistri', 'Mediocampista'],
    ['Darwin Núñez', 'Delantero'],
    ['Facundo Torres', 'Delantero'],
    ['Maxi Gómez', 'Delantero'],
  ]),
  makeTeam('IRQ', 'Irak', '🇮🇶', 'L', false, [ // verificar clasificación
    ['Jalal Hassan', 'Portero'],
    ['Mohammed Hameed', 'Portero'],
    ['Fahad Talib', 'Portero'], // verificar
    ['Ali Adnan', 'Defensa'],
    ['Rebin Sulaka', 'Defensa'],
    ['Hussein Saber', 'Defensa'],
    ['Ahmed Ibrahim', 'Defensa'],
    ['Saman Qurizagh', 'Defensa'],
    ['Mustafa Nadhim', 'Defensa'], // verificar
    ['Amjed Attwan', 'Mediocampista'],
    ['Safaa Hadi', 'Mediocampista'],
    ['Mohannad Ali', 'Mediocampista'],
    ['Amjed Kalaf', 'Mediocampista'], // verificar
    ['Bashar Resan', 'Mediocampista'],
    ['Hussein Falah', 'Mediocampista'], // verificar
    ['Aymen Hussein', 'Delantero'],
    ['Emad Mohammed', 'Delantero'],
    ['Ahmed Yasin', 'Delantero'],
  ]),
];

// Índice de equipos por código
const TEAMS = {};
TEAMS_DATA.forEach(t => { TEAMS[t.code] = t; });
ADDITIONAL_SECTIONS.forEach(t => { TEAMS[t.code] = t; });

// Grupos ordenados
const GROUPS = {
  A: ['MEX', 'ECU', 'SEN', 'ROU'],
  B: ['CAN', 'MAR', 'CRO', 'PAN'],
  C: ['BRA', 'JPN', 'CMR', 'NZL'],
  D: ['USA', 'KSA', 'SUI', 'GHA'],
  E: ['GER', 'AUS', 'SRB', 'HON'],
  F: ['NED', 'KOR', 'CUW', 'RSA'],
  G: ['BEL', 'ITA', 'BOL', 'NGA'],
  H: ['ESP', 'TUR', 'PAR', 'CPV'],
  I: ['FRA', 'POL', 'JOR', 'SCO'],
  J: ['ARG', 'JAM', 'CRC', 'EGY'],
  K: ['POR', 'COL', 'UZB', 'COD'],
  L: ['ENG', 'DEN', 'URU', 'IRQ'],
};

const TOTAL_BASE = 994;
const TOTAL_TEAMS_STICKERS = 960; // 48 × 20
const TOTAL_ADDITIONAL_STICKERS = ADDITIONAL_SECTIONS.reduce((sum, section) => sum + section.stickers.length, 0);
const TOTAL_ALBUM_STICKERS = TOTAL_TEAMS_STICKERS + TOTAL_ADDITIONAL_STICKERS;
const TOTAL_SPECIAL = ADDITIONAL_SECTIONS[0].stickers.length;
const TOTAL_EXTRA = 22;
const STICKERS_PER_PACK = 7;
